add demo image 
update chagelog 
ignore Update ' modules / apps / foundation / portal / . 
missing icon 
LRQA - 16928 Set a default value for the ' test . skip . tear . down ' property in ' test . properties ' 
Add depart icon in itinerary step row 
make shortcuts white for selected menu items 
bump engine . io - client 
removing comm files from jre since they needn ' t be in there 
Remove Notification Center observers on dealloc 
Updated changelog 
CursorToBulkCursorAdapter . close must call mCursor . close instead of mCursor . deactivate . 
ignore Update ' modules / apps / web - experience / iframe / . 
Fix readme 
prepare release checkstyle - 7 . 1 
Switch master to 4 . 1 . 0 . BUILD - SNAPSHOT 
update Flow to version 0 . 5 . 1 
Fixed test 
add back missing images 
Ignore Maven build directory 
Removed non - needed imports 
Add missing section include for reindex breaking changes 
setting version to 1 . 0 . 71 
ignore Update ' modules / apps / foundation / roles / . 
Remove circleci config 
specify Main - Class in MANIFEST . MF directly in updater module to simplify build scripts 
Add a Javadoc pointer from DiscreteDomain to DiscreteDomains . 
ignore Update ' modules / apps / foundation / petra / . 
LRQA - 16988 Remove unused property 
Added another location of metastore_db in . 
Added changelog for server - advanced for 1 . 7 
just fixing an internal test name , but I noticed this got an NPE when I was running . 
avoid NPE when trying to create a file that already exists 
Ignore Eclipse files 
ignore Update ' modules / apps / foundation / portal - cache / . 
Add package index for support components . 
Updated changeling . 
Fix systemui crash on Xoom startup 
ignore Update ' modules / apps / web - experience / asset / . 
ignore Update ' modules / apps / foundation / contacts / . 
prepare for next development iteration 
bump engine . io - client 
fix error in docking station on chunk unload , fixes # 2898 
Prepare version 18 . 0 . 2 . 
Prepare 3 . 0 . 0 . 
do not use the lastest tool on travis 
Copy original head elements to the new < head > . 
updated wiki snapshot 
DO NOT MERGE - Updated media playback transport controls ( b / 3116268 ) 
Change xml tags order . 
Changed add ( ) in SynchronizedHistogram to synchronize ( making copy ( ) safely synchronized as a result ) . 
Add missing file for CASSANDRA - 3563 
try hack sdk sign 
Allow text input focus in WebView 
Added STORM - 827 to Changelog 
update to the latest support lib 
ignore Update ' modules / apps / collaboration / document - library / . 
Bumped version number to 1 . 4 . 1 
Ignore tests in release perform as they ' re already run in the prepare stage 
add index on unregistered_phone_contacts 
update docs 
remove mail notifications ( for now ) from travis 
corrected PImage . setModified ( ) so mx2 and my2 are width - 1 and height - 1 , 
Remove extraneous space . 
Added Recognizer . removeErrorListeners ( ) to Recognizer . py 
upgraded guava to 14 . 0 
fixed build . properties 
setting version to 1 . 0 . 61 
Fix build issues 
Add changelog to track high level changes of each release 
Added files via upload 
ignore Update ' modules / apps / foundation / contacts / . 
Removed sleep from clickOnView ( ) as requested by issue - 333 
Just to get correct commit rights on buildbox 
Add an assert to RowDataResolver # getData ( ) 
bumped versions , preparing for release 
Add screenshots 
Added missing gen folder 
LPS - 66848 Add missing Gitignore 
JAL - 36 Add image notes to good for proprietary licenses 
update linux - x86 natives 
Removed tag flyway - parent - 1 . 6 
Shrink default path cache size 
Add STORM - 829 to CHANGELOG . md 
IDEA - 133873 refresh changed files after commit , because they can be modified by hooks 
fixed # 860 
ignore Update ' modules / apps / foundation / login / . 
Capitalize tag names by default 
LPS - 3461 , read long groupId as long instead of string otherwise it will break in JPA 
Changed version file to Dev Build to prevent confusion . 
Remove unneeded SideOnly . 
prepare release checkstyle - 7 . 1 . 2 
Added gitignore . 
ignore Update ' modules / apps / web - experience / asset / . 
add STORM - 2079 to CHANGELOG 
Added Android SDK Platform with API level 16 to Travis build file 
ignore Update ' modules / apps / web - experience / export - import / . 
Rebuilds the JNI library jnmaccoreaudio on and targeting OS X 10 . 7 . 
decompiler updated ( line separators ) 
dont fail client module because there are no tests 
Require Maven 3 . 0 . 
remove rogue prinltn 
Updated CHANGELOG . txt . 
Updated gitignore 
typo cont ' d ( remove deprecated method in trunk ) 
ignore Update ' modules / apps / foundation / portal - scripting / . 
Remove AUTHORS file . 
Suppress some deprecation warnings 
updated todo . txt 
Set scrollsToTop = NO for UITextViews 
update Readme 
testing out travis as ci 
Bump SpongeCommon for various updates and fixes . 
added Travis CI configuration . 
ignore Update ' modules / apps / web - experience / trash / . 
Add a simple travis configuration 
Add shell script for zan 
don ' t show empty Python code style settings page ; fix Python preview text 
ignore Update ' modules / apps / foundation / login / . 
Update build tools for travis 
fixed NPE when setFrameTag ( ) is called before setApkFile ( ) . 
update parent pom 
Fix Boost install script 
Increment gradle build tools 
initial commit - dev guides 
Create new XYMarkerView ( # 2029 ) 
Added STORM - 1837 to Changelog 
Updated gradle release plugin dependency to 0 . 1 
ignore Update ' modules / apps / collaboration / wiki / . 
Updated binaries 
bump version to 1 . 8 . 7 
fixed test 
Remove image sample 
add todos 
ignore Update ' modules / apps / foundation / portal - search / . 
update libwebp 
LPS - 67914 - Create project build . gradle 
Updated FML 
Specify a local . 
ignore Update ' modules / apps / collaboration / comment / . 
set component configurations correctly for trident spouts 
LPS - 39662 Add @ Override 
update CHANGES 
Fix permissions 
now removed connect - js submodule 
Bump version to 1 . 0 . 2 - SNAPSHOT 
change EditDistanceJoiner . jar to newest version 
remove not null constraint on config_parameters value 
ignore Update ' modules / apps / collaboration / message - boards / . 
Setting default name for multi - project 
starting 0 . 5 . 5 - SNAPSHOT 
Fixed double - callback for cached images 
update readme 
ignore Update ' modules / apps / web - experience / layout / . 
Smack 4 . 2 . 0 - alpha2 
Fix build . 
ignore Update ' modules / apps / web - experience / trash / . 
TestApp no longer overrides ' grails . env ' setting - fixes GRAILS - 1988 . 
LRQA - 16948 Modify the jserrorcollector xpi file in poshi runner 
Updating Alloy to rev . 74879 
Removed debug output - X from install . sh . 
updated version name / code 
updated CHANGES 
Remove the phase in order to have sources signed for deployment 
added info option to travis to output more information 
remove jdk6 from travis options for our java 7 supported branches 
Updated the . 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
Cast a vote . 
rename unit - tests execution to default - test 
Remove ntlm module from pom 
Updated changelog 
Add Application class . 
ignore Update ' modules / apps / foundation / portal / . 
Updated changelog 
removing jar 
LPS - 68306 Add new marker file to registry - api 
removes CHANGELOG . ja . rdoc from the manifest 
Added makeGLMModel call to python . 
list comp expr has a type 
remove blade - sample 
Fix ticking on the server 
Fixed test data 
Updated demo art 
ignore Update ' modules / apps / web - experience / application - list / . 
Added missing test data 
setting version to 1 . 0 . 63 - SNAPSHOT 
update travis 
added missing image 
Fix the seed for DRF JUnit . 
Updated changelog 
ignore Update ' modules / apps / collaboration / directory / . 
Taken out old activity 
add gitignore 
When using IDEA 10 , I cannot run any code that uses native libraries via JNA . 
Removing unused imports . 
Fix Build 
Removed tag roboguice - 1 . 1 . 1 
ignore Update ' modules / apps / web - experience / journal / . 
added STORM - 525 to changelog . 
added STORM - 525 to changelog . 
Updated Changelog for STORM - 421 
Adds smackx - debug to our smacklib to make debugging easier when necessary 
Fixing failed tests 
restored projectName property to support backwards compatibility with plugins etc . 
Ignore IDEA directory 
ignore Update ' modules / apps / collaboration / wiki / . 
ensure cursor is visible after execution point advances 
regenerate gradle - wrapper . jar using 1 . 10 
typo , removed sys accidently a couple days back 
regenerate gradle - wrapper . jar with 1 . 9 - rc - 4 
Each tested chaos monkey script must now include the name of the monkey 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
missing header for linux 
Refactored quartz plugin . 
Change gitignore file . 
bump version to 1 . 5 . 0 
Use local installed pybabel and i18next - conv 
Added tag 0 . 2 for changeset f241352a0b11 
made executable 
Remove duplicated java option concats in common . sh 
Built the latest snapshot 
Changed version 
Added relative path to the parent POM so that the user won ' t need to 
add stub subway icon ( just using one of the rail ones for now ; should design a new one at some point ) 
Add isPlaying ( ) to animation objects 
Reseting a project . properties file 
Fixed readme typo , thanks @ alashow , closing # 259 
LPS - 52093 moves icon 
Prepare next release v0 . 91 . 2 - SNAPSHOT 
adding words suggested by users 
Changed version number so I could push the new version to dist . 
 @ Deprecated does not have effect in Groovy 
Add fatter divider on xhdpi devices . 
Update the footer indicator paint when footer color is set programmatically . 
Avoided building tags , this way we avoid building a commit twice . 
ignore Update ' modules / apps / foundation / frontend - css / . 
Create README . md 
Prepare version 24 . 
enabled test to see if test coverage is going to be triggered 
fix merge conflict resolution 
Remove spurrious line clamping speed to average . 
ignore Update ' modules / apps / foundation / portal - template / . 
ignore Update ' modules / apps / foundation / portal - search / . 
ignore Update ' modules / apps / collaboration / wiki / . 
ignore Update ' modules / apps / foundation / roles / . 
Fix typo which cause stack overflow if children ( ) was called 
LPS - 32038 Remove old jakarta - regexp . jar from lib / development since it ' s now in lib / portal 
Ignore annotations 
Force these dirs to exist . 
Add support lib to SeriesGuide project , too . 
Add * . 
LPS - 34188 Add missing list close tag in the export layouts form 
Remove debug code . 
removed bold font style 
Fixed a bug with backsided objects . 
Fix FrameworksServicesTests . apk to include libc + + . 
retroweave smack libs 
set correct version 
Set the source encoding to UTF - 8 to remove a maven warning when building 
Updated samples . 
moved glm pyunit to NOPASS due to intermittently failing more often than desired . 
Added translation using Weblate ( Swedish ) 
Added jpg version of logo 
update gutter size after setting LineNumberConvertor 
added sitemesh jar 
See diff 
Remove unnecessary dependency on Clang headers . 
Branch action has only All option 
LPS - 50254 redo sdk to have better logging 
JAL - 35 Add image notes to non - proprietary licenses 
Change ForcedResizableInfoActivity to handle config . 
removing stuff useless for release 
ignore blogs - demo 1 . 0 . 0 prep next 
ignore Update ' modules / apps / foundation / users - admin / . 
Removed root logging configuration from logback config . 
Added gitignore . 
Fixes a failure to preview the video device on GNU / Linux . 
Add common Eclipse ignore files 
Delete outdated directory creation in build . xml 
added meteocons cheatsheet 
Fix mouse released . 
Move QueueFile to ' io ' package . 
removing MMultApp jars from repository 
added favicon 
Make SwitchPreference switch more Material 
add help id 
Add scope = test to hsqldb ( fixes # 330 ) 
Keep PhoneStatusBar default constructor around . 
change the default release scope to be patch 
Updated changelog 
ignore Update ' modules / apps / marketplace / . 
optimized imports 
Add ignore for the maven - ant - tasks . 
Still having problems with version - updated to a new one . 
updated credits 
Added STORM - 794 to Changelog 
fixed PY - 6543 Django manage . py commands not working 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Add new RIL command for sending ack to solicited async and unsolicited msg . 
IDEA - 117674 please rebuild and commit runnerw . exe 
update changelog 
ignore Update ' modules / apps / collaboration / microblogs / . 
prepare release storm - hbase - 0 . 1 . 2 
Made empty constructor for ModMetadata public 
skip tests in compiling alluxio for hadoop 
removed built in color from layout 
Publish 0 . 4 . 0 . 
Updated codelock assets 
Don ` t hardcode the android sdk path in the build script before you push ( im looking at you Dave ) 
Updating Alloy to rev . 74879 
Push version to 16 - beta8 , 15020 . 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
Upgraded maven - release - plugin to version 2 . 1 . 
push new builder top on texture 
Updated build . gradle to buildToolsVersion " 21 . 1 . 1 " 
ignore Update ' modules / apps / web - experience / asset / . 
was missing beta_features = True 
Ignore Eclipse project files . 
Adding maxmemory setting for javadoc generation 
Added missing gen folder 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
Adding STORM - 1372 to CHANGELOG 
Rebuilds libAEGetURLEventHandlerAgent . jnilib for Mac OS X 10 . 4 compatibility . 
Updated version 
Added STORM - 1219 to Changelog 
icon - help shows tooltip with HTML code 
Move test to correct place . 
ignore Update ' modules / apps / web - experience / staging / . 
BIO doesn ' t use comet but align code with NIO / APR . 
update doc 
Added Gradle installation lines 
Fixed vararg parser typo . 
Remove unused import 
Add tag required by schema to Cobertura configuration . 
prepare for next development iteration 
added dependency on decl_auth gem 
added moco logo 
fix build for example project 
LRQA - 14606 Add test property for calendar - portlet 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
removing empty files 
fix test data to match actual stops 
Set minSdkVersion to 8 for DroidGap project 
Improve MongoDB script 
Fixed lint error that was failing travis 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
gh - 49 Build fix ( sears ) 
ignore Update ' modules / apps / screens / . 
updated minidns 
IDEA - 117674 please rebuild and commit runnerw . exe 
Fix manifest 
add STORM - 2070 to CHANGELOG 
Remove whitespacek 
increased session idle timeout to 40 min 
Updated changelog 
LRQA - 24908 Add new property ' extraapps . plugins . includes ' for functional tests 
Log exception messages on test failure . 
Delete design_pattern_relationship . 
Create PULL_REQUEST_TEMPLATE . 
We don ' t need pthread 
ignore Update ' modules / apps / foundation / hello - world / . 
Remove CCC 
LPS - 67914 the other themes don ' t have this 
Fix mistype 
Added ' How it works ' schematic 
Adding a ' . 
add info about " Android - AppMsg - Gradle - Sample " in README . md 
Fix # 2751 
Added twitter and rand example output files to . 
Stop previous ringtone when silent is selected . 
removing stuff useless for release 
Added getContext to FakeDialog 
Populate resolution menu when it has rendered 
Pushed 2 . 8 . 1 again , fixed a small UI issue . 
ignore Update ' modules / apps / collaboration / item - selector / . 
LPS - 55274 don ' t check this in 
Fix test to also include the mapper - size 
Test travis CI . 
added STORM - 1687 to Changelog . 
add @ 2x node placeholder for HiDPI non - Retina devices 
Possibly fix # 94 
Add final newline to editorconfig . 
Reset the inverse of the modelview in resetMatrix ( ) . 
changed table headers to nowrap 
Added SQLDialect 
Add stacktrace for travis option . 
LPS - 47589 Fix broken upgrade 
prepare for next development iteration 
Renamed test process to make the test run on case sensitive operating systems 
update msn lib 
ignore Update ' modules / apps / collaboration / wiki / . 
Granular navigation uses mContentDescription instead of getCpontentDescription ( ) s 
Add test - reports / to gitignore 
Upgraded parent version . 
remove logging message from getScrollingCompentationType 
ignore Update ' modules / apps / foundation / frontend - theme / . 
adding jna for native library access 
Upgrade netflixoss Nebula plugin to 3 . 2 . 2 
Ignore spring - build ' docbook ' directory 
Changed deploy_snaphsot permission ( # 41 ) 
Added openjdk6 to unit tests 
Ignore my TODO list 
ignored a few more IDEA files 
ignore Update ' modules / apps / screens / . 
Removed unnecessary asset 
removed misplaced test file 
Permit the folder list item to expand vertically . 
prepare 0 . 6 release 
Number the reference 
Added files via upload 
Make RUnit NOPASS until further discussion of behavior change . 
Added missing images 
add icon 
exclude * . 
add change 
Have a bottom actionbar in the Search activity to be consistent . 
Skip the enforcer plugin in the examples 
Fix a rare NPE crash in Android 2 . 
FastArray doesn ' t overwrite toString ( ) method 
Adding Client Load - Balancing diagrams 
updated wiki snapshot 
Remove extra spacing 
Remove call to FileDescriptor . sync in Compiler . writeClassFile 
Temporarily disable MixinC00Handshake 
run travis ci whit ' gradlew check ' 
ignore Update ' modules / apps / foundation / portal / . 
LPS - 52368 move icon 
Don ' t allow negative numbers in ToneGenerator toneType parameter 
LPS - 58341 The * . 
remove x attribute of java file 
ignore Update ' modules / apps / web - experience / site - navigation / . 
Remove obsolete file 
Added parsing of Cython include statements 
LPS - 42360 break - all will prevent overflow from containers 
fixed typo in MultiTerrainLodControl causing terrains not to be removed 
Added get point method to Line3D . java 
Create README . md 
was ignoring error in TCPServer . 
Updated changelog 
gh - 49 Build fix ( sears ) 
Removed unused resurce 
remove unused logger 
Added c2s truststore file . 
attach testng sources 
ignore Update ' modules / apps / collaboration / document - library / . 
added new easymock library that can mock abstract and regular classes 
Fixes java 1 . 5 error . 
Add hammer icon for brute force 
Revert " Caching dependencies to speed up PR builds " 
do not force everyone into the null checking 
ignore Update ' modules / apps / foundation / frontend - js / . 
ignore Update ' modules / apps / foundation / login / . 
remove build tools from NOTICE 
Keep org . jetbrains . kotlin . 
ignore Update ' modules / apps / foundation / portal - settings / . 
Ignore Eclipse files 
Updating Alloy to dcea66d ; LPS - 25276 
turn off attempted fixes 
remove warning 
added idea ignore config 
LPS - 47461 Add entry - action style 
Added files via upload 
ignore long time test 
Removed background color from settings row in drawer 
LPS - 54434 prepare next version 
ignore Update ' modules / apps / marketplace / . 
ignore Update ' modules / apps / foundation / roles / . 
Add CAP_BLOCK_SUSPEND to system server 
ignore Update ' modules / apps / sync / . 
Log more frame data when profiling GL apps 
Move widget preview drawables to drawable - hdpi . 
LPS - 65425 Delete " deploy " dir while cleaning 
Remove redundant version number from application . properties ( grails plugin ) 
Ignore derby log anywhere 
LPS - 54533 moves icon 
update applet zip 
add new updated octicons 
ignore Update ' modules / apps / foundation / frontend - js / . 
updated webflow jars 
Fix proguard flag file dependency . 
Add link to 0 . 146 release notes 
Fix proguard 
Updated screenshots 
Added STORM - 1258 to Changelog 
ignore Update ' modules / apps / collaboration / message - boards / . 
ignore Update ' modules / apps / collaboration / wiki / . 
update changelog 
add notes about JDI 
Fix problem with xxhdpi 
Removed unnecessary file . 
Bumping rest - client . 
ignore Update ' modules / apps / foundation / frontend - js / . 
Added the HL7 DataFormat to the jaxb index 
Fixed zeroClipboard . min . js 
LPS - 65749 prep next , use latest 
Removed javadoc dependency from javadocJar method to avoid automatic javadoc build 
Add final modifier to ShortcutBadger class to avoid anybody to extend it 
Jetty9 - Reduced test logging . 
Fixed CodeNarc . 
Add CPUFREQ_STATS event tag 
Disable non - JDK8 builds on Travis 
Fixed a compile error . 
Updated Changelog with STORM - 612 
Add an afterMainOptimizations marker to DefaultPassConfig 
remove spurious import 
send non - physical change event + track invalidation of elements in JavaResolveCache 
Updated REAME . md . 
updating to Gremlin 0 . 8 
ignore Update ' modules / apps / web - experience / asset / . 
Bump react - native - cli version 
ignore Update ' modules / apps / collaboration / blogs / . 
Fix funnel bar positioning 
Remove debug logging in divider draw 
Restore untrusted glStencilMask value on resume after functor 
Revert " LPS - 36642 rebuild ruby - gems " 
ignore loading . gif for push dialog when generating icons classes 
Missing key 
ignore Update ' modules / apps / collaboration / notifications / . 
Fixed deserialization problem in DatePicker . 
Make a field final . 
update travis . yml 
reset p2p0 interface channel as well 
prepare for next development iteration 
set defaultPublishConfig to debug - in case we had source dependencies to this module 
Built the latest snapshot 
ignore Update ' modules / apps / collaboration / comment / . 
add resources back ( missing drools file otherwise ) 
Fix checkboxes for message_list_item_touchable . 
Refactored quartz plugin . 
update target API 
ignore release . properties 
Add description 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
prohibit " Schafmittel " 
Fix bug 45195 . 
added ForbidAnnotationElementValueCheck 
Updated sample with new basic dialog with long scrollable content for release 0 . 0 . 6 
bump pegasus to 1 . 10 . 6 
Updated changelog 
Fix IntentPickerSheetView example wrong syntax 
Set jdiff version 
CORE - 2136 Mysql must quote PARTITION as a keyword 
Making default Socket timeout 20s ( from 8s ) . 
update lib version 
Remove spaces . 
Ignore project configuration files for NetBeans 
add changes entry about snapshot functionality 
ignore Update ' modules / apps / collaboration / directory / . 
Add slack integration for travis 
rename file so its title has a space in it 
Remove unused constant from TWLayoutManager 
Fix finalization 
commented out the package tag used by javadoc plugin , because javadoc was confused 
ignore Update ' modules / apps / foundation / hello - velocity / . 
add site deploy note 
updated ChangeLog 
fix typo in install - packages for win os 
Fix a typo . 
evaluate the injected javascript 
Prepare next release 
Fix permissions 
add support jar 
Rewrote some code for switching to konference and freeswitch 
Updated gradle plugin . 
bump version for move to Apache incubator 
Add CodeNarc rule exclusion 
Do not load twice web services from plugins for a fresh installation 
delete junk 
Fix typo reported by @ earthgecko 
Add string type to outerHTML . 
treat ap0 as wifi hotspot interface 
Add twitter icon 
Move local_mapred_error_cache . 
default native proto to correct port in Config 
Restore missing usage assignment in AudioAttributes 
call the callback on sdkInitialize 
bumped version 
don ' t pass remote - shell - port parameter twice 
Delete an extra line 
Adding a newline at the end of the file . 
Remove duplicate eclipse classpath entry from build . gradle 
Input Whitespace ( is used in many UTs ) now compilable 
Modify Dockerfile 
ignore Update ' modules / apps / collaboration / flags / . 
add alpha channel to project sharing icon 
Added STORM - 765 to Changelog 
remove - - debug option 
fixing bash in installDeps 
Fix version range for restict - doclint . 
Updated changelog 
Fixed UIExplorerStateTitleMap . js being . 
Use Travis - CI ' s container based infra 
Push version to 12 - beta8 , 228 . 
updated build . properties for 0 . 3 
add # 1551 to CHANGES 
update xsoup to 0 . 2 . 1 # 75 
woops java type checks ! 
update travis 
explicitly include version in issue template 
Updated reference to library to fix problems in login view when fixing typos in URL path 
Use new AndroidUtils . executeOnPool . 
ignore Update ' modules / apps / web - experience / portlet - configuration / . 
Avoid splitting overloaded methods 
fixed ignores 
removed symbolic link to action bar sherlock library 
update changelog 
prepare release HikariCP - 1 . 3 . 5 
add pythong / . 
Move PointSetTest to the same package as PointSet . 
Fix PyCharm edu icon 
Adding updates for the icu project 
updated version 
Setting build group and version 
Added missing gen folder 
removed beta 
add NOTICE file 
ignore Update ' modules / apps / foundation / portal - search / . 
Added new ask attribute to Item and new " remove " subscription to Item . 
Set memory for compiler as otherwise it sometimes fails here 
Added person . 
auto synchronize rng 
Fix # define conflicts with mingw - w64 
Fix setting of media direction in conference - information . 
Add additional key for fullscreen on iOS7 
Update build tools to 21 . 1 . 1 . 
Bump the jacoco version . 
Update doc commit pointer 
added ignored words . 
HHH - 7147 - ServiceRegistry is starting services twice 
update native lib 
LPS - 22971 Default it to true 
Build tools version updated to 22 . 0 . 1 
If ExceptionsManager . handleException throws , throw the original error 
Changed field type of username in jiveGroupUser . 
Prepare version 29 - beta3 . 
Add Eclipse 4 . 5 new workspace folder to . 
Fix gif url 
add netbeans folder to gitignore 
start 2 . 2 - dev 
Add Q3 2011 ADL slides to docs / shareables / adl 
prepared for next development iteration 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
WFLY - 6768 ServletResourceManager does not implement isResourceChangeListenerSupported correctly 
Renamed Hopper to Chute as discussed 
Added STORM - 1348 to Changelog 
remove runit_NOPASS_Rdoc_prcomp . 
Included Android gen folder to ignored files . 
Revert travis change as they do not support java6 anymore 
Added " elastics " client for javascript 
adding xsltproc 
update translation 
Fix fillLiquidContainer - return null , not the empty container for 
LPS - 17220 Wiki page attachments links contain p_p_auth 
activate connections tab when new connection is opened 
Added STORM - 765 to Changelog 
Don ' t resolve the base path before passing it to the project generator . 
Change itest to match intentionally different behavior . 
updated ChangeLog 
Use the better IOException type ( any other exception is totally unexpected ) . 
Added toString ( ) method in NeoApp . NeoAppRelationshipType . . . otherwise 
Add mk to " Shell script " group 
Fix mislabeling issue 
Switch basic auth back on in web - secure 
Fix React warnings 
Fix added version termvectors . asciidoc 
turn off active by default on tests ( # 1843 ) 
LRQA - 24374 Add a new ' portal . release ' property to mark all portal tests to be ran in the release job 
build stable branches 
fix failing test , account for url - mappings - report 
Removed license files from jars , was screwing up the build 
ignore Update ' modules / apps / collaboration / item - selector / . 
update travis 
Fix Test 
Removed snapshot dependency for release . 
rename main file 
Updating Alloy to rev . 74879 
ignore Update ' modules / apps / foundation / frontend - theme / . 
updated apk with the examples of the last version 
Record correct shell test failure times 
Fix SSLCertificateSocketFactory . getDefaultCipherSuites . 
also define BOOST_FILESYSTEM2_NARROW_ONLY 
ignore Update ' modules / apps / collaboration / wiki / . 
 " from exec argument . . . was creating a problem on Linux . 
Add @ SmallTest for continuous tests . 
implement enterTemp using another enterTemp 
adds awesome image courtesy of the internet 
Fix jar signer not applying to universal packed in the installer . 
Don ' t use stlport . 
add session constant for user home page 
Remove redundant constructor . 
ignore Update ' modules / apps / foundation / petra / . 
Added STORM - 316 to Changelog 
Add additional options . 
Fix indent for unordered lists as well 
Specify version name for subproject properties 
Updating Alloy to dcea66d ; LPS - 25276 
Updated the binaries . 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
Add hdpi and xhdpi dark collected icon . 
Do not autoreload quick values by default 
Remove POS JJ from ' ie ' 
Create README . md 
Allow travis containers . 
Switch master to 4 . 1 . 0 . BUILD - SNAPSHOT 
 ( nojira ) edit travis working directory ( from that given in instructions ) 
ignore Update ' modules / apps / web - experience / product - navigation / . 
Updated eurosport cert so that SSL tests now works again 
Updated freebox os to v3 . 0 of Freebox API and proposal of transformation localization 
Move the heroku env config out of the procfile . 
ignore Update ' modules / apps / foundation / frontend - js / . 
disable doclint on JDK8 
Prepare next development version . 
Added missing gen folder 
Updating Alloy to rev . 74879 
ignore Update ' modules / apps / web - experience / export - import / . 
Fix nullptr exception . 
new svnkit , build 5066 . 
ignore Update ' modules / apps / marketplace / . 
corrected versionName and versionCode to reflect base branch release6 . 0 
indri shared lib 
Fix leak of stackTrace in java / lang / Throwable . 
Updating fabric directory from repo to public 
Add a META - INF / services file specifying JimfsFileSystemProvider as a service provider . 
Replace demo7 . gif 
Add config for TravisCI 
Fix focus issues with dialpad in the call dialog . 
updating parent pom 
Add BAD_PACKAGE_PROPERTY_ACCESS DiagnosticType to the VISIBILITY DiagnosticGroup ( which transitively adds it to ACCESS_CONTROLS ) . 
Add Travis configuration . 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
Updated gitignore 
Fix broken build 
Fix ant checkstyle 
Restore untrusted glStencilMask value on resume after functor 
updated credits 
ignore Update ' modules / apps / foundation / portal - configuration / . 
fixed misnamed setter 
Upgraded the version in the parent pom references in our example components to 3 . 
bumped version 
Bump SpongeCommon for various updates and fixes . 
Updated changelog with new entries . 
Move to nebuladotNetflixoss 2 . 2 . 5 
ignore Update ' modules / apps / web - experience / journal / . 
add # 1551 to CHANGES 
Revert " Restrict S3 deployment to actual tarball " 
LPS - 34446 Fix typo 
added test package to androidTest folder as system link to generate the true coverage 
Add an afterMainOptimizations marker to DefaultPassConfig 
 @ Deprecated does not have effect in Groovy 
fixed PY - 7294 Invalid warning about encodings in Python files 
update usage plugin 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
ignore Update ' modules / apps / foundation / portal - security / . 
Fixed a potential CPU cache issue . 
Uses device UID or name ( instead of index ) for PortAudio CaptureDeviceInfo locator . 
enable coverage to work with java 8 ( IDEA - 96364 ) 
Removed unnecessary tag 
Revert " Bumps commons - pool2 version to latest " 
Fix sample 
ZEPPELIN - 359 add NOTICE and DISCLAIMER in the binary package 
Disable other flaky Apple app test integration test 
Adding NightlyBuildID . java to . 
Add STORM - 1426 to Changelog 
Add flags needed to switch Jack to 1 . 8 for CTS targets 
undid test fix ( syntax in question is now supported ) 
Updated file names 
bump version 
Fix NPE in PackageParser 
missing return in svg ' s getCoords 
LPS - 32038 Remove old jakarta - regexp . jar from lib / development since it ' s now in lib / portal 
add eric to contributors 
Built new snapshot 
Bump up revision number . 
Fix mobile sites ' viewport in fixed viewport mode . 
ignore Update ' modules / apps / foundation / petra / . 
Fix config 
ignore Update ' modules / apps / foundation / portal - cache / . 
Prepare next development version . 
config not needed aynymore 
Use 32dp size image for PictureInPictureAction icon 
Add support for SSL 
updated banner to show 0 . 63 - Beta 
Updated changelog 
ignore Update ' modules / apps / foundation / frontend - js / . 
Fixes java 1 . 5 compatibility . 
Adding STORM - 1372 to CHANGELOG 
removed required flag for gemDirectory 
ignore Update ' modules / apps / web - experience / site / . 
ignore Update ' modules / apps / web - experience / site / . 
added plain icon screenshots 
Upgrade JUnit to 4 . 12 
Updated changelog 
add words suggested by users 
remove background color from welcome fragment 
sip logo and sip connecting icon 
ignore Update ' modules / apps / foundation / web - proxy / . 
Create README . md 
Delete default README 
removed cycleTables from upgrade 
prepare release acra - 4 . 6 . 0 
Create CONTRIBUTORS . md 
update readme 
Remove code highlighted as unused by UCDetector 
Bumped curr . release to 1 . 1 . 1 
added meteocons cheatsheet 
ignore Update ' modules / apps / collaboration / message - boards / . 
Added tag 0 . 1 for changeset d04a8ef4ccb0 
Updated gitignore to not give a rat ' s ass about the generated gradle wrappers . 
Removed lib / . 
Updated library paths 
upgraded netty to 4 . 0 . 22 
LPS - 19211 Missed build . properties 
LPS - 31796 Copy the classloader when creating the proxy 
Corrected the groovyBundleVersion in build . properties for the new 1 . 8 . 0 - beta - 1 branch . 
ignore Update ' modules / apps / foundation / frontend - theme / . 
replace Future < T > with T in EJB implementation 
Added missing property for playWhenInactive . 
Remove unused files 
remove avalon from pom temporary 
ignore Update ' modules / apps / collaboration / bookmarks / . 
Updated gradle release plugin dependency to 0 . 1 
updated ChangeLog 
Uses device UID or name ( instead of index ) for PortAudio CaptureDeviceInfo locator . 
Using released version of jetty - enforcer - rules 
Added ICA root certificates . 
Delete " idea . properties " 
Resize sample image 
Fixing the build for real . 
ignore Update ' modules / apps / web - experience / asset / . 
Create README . md 
remove x attribute of java file 
add gitkeep for assets 
ignore calevent - importer 1 . 0 . 5 prep next 
Added idea output directory to . 
Add PLAY and PAUSE keycodes and remove PLAY_PAUSE keycode . 
update win32 - x86 native 
Fixed Android Support library for Cropper . 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
Set travis jdk to java8 
Fix single test 
remove unused const to clear compile warnings 
update sparc natives 
Fix level of section in build tool plugins documentation 
setting version to 1 . 0 . 106 - SNAPSHOT 
Added OGNL expression object graph expression language jar 
applied new thrift jar 
added missing imports 
ignore Update ' modules / apps / foundation / portal - scripting / . 
updated packrat bootstrap icon 
Fix broken test data file 
missing curly brace in ip_range aggregation example 
added baseName for uberjar task 
add # 2557 to CHANGES 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
LRQA - 23204 Add new component for testing plugins deployment 
don ' t clear disk cache on finish 
Fix permissions 
Add unsubscribe to AbstractViewModel . 
ignore Update ' modules / apps / collaboration / directory / . 
ignore Update ' modules / apps / foundation / petra / . 
Fix name of java executable 
ignore Update ' modules / apps / collaboration / wiki / . 
Updated changelog 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
fixed changed class name in launcher 
Fix dll location search . 
Add additional clirr config 
removed roles from neo4j recipe , since they can not be part of a recipe 
Updating Alloy to rev . 74879 
Upgraded parent version . 
Fix race condition in ZRTP state engine 
kill subprocess when ShellSpout . die ( ) called 
Added STORM - 1270 and STORM - 1274 to Changelog 
Smack 4 . 0 . 6 - SNAPSHOT 
Bump up version 
Updating Alloy to rev . 74879 
placed the completed ( ) call under the right braces 
Updated changelog 
ignore Update ' modules / apps / foundation / frontend - css / . 
CAMEL - 1932 removed slf4j - simple dependency from camel - mina pom 
enable on_start notification always 
Make log4j an optional dependency 
add STORM - 1735 to CHANGELOG . md 
Remove cruft 
ignore Update ' modules / apps / marketplace / . 
Fix unnecessarily non - static inner class to static inner 
don ' t index unsaved files ( ie , no context ) 
Fix upload script . 
Removed unnecessary indirect call in NioSocketChannel . isConnected ( ) 
Undo wiki images 
Don ' t maximize viewer ' s window by default 
Added files via upload 
Releasing OrientDB 2 . 1 - rc6 
added missing BenchmarkRunner config for svenson JSON databind 
Upgrade java - util dependency to include " ruby " time 
Added reference to JMM 
Fix a constructor " 
ignore Update ' modules / apps / collaboration / bookmarks / . 
prepare release HikariCP - 1 . 1 . 5 
Adding missing semicolon ; 
Add GC thread to RSGL . 
ignore Update ' modules / apps / foundation / server / . 
Only CI build the master branch 
Added commitChanges before other return statement of annotateExternally ( ) 
Changed version number so I could push the new version to dist . 
don ' t set the application title in the library 
Rename CIELCHEvaluator . java to CIELChEvaluator . java 
Bump SpongeCommon for various updates and fixes . 
ignore Update ' modules / apps / web - experience / layout / . 
Remove impute . flow from index . list 
Bumping rest - client . 
FlowManager should set mDatabaseHolder to null on destroy # 251 
ignore Update ' modules / apps / collaboration / message - boards / . 
Only need whassup jar file 
ignore Update ' modules / apps / foundation / frontend - css / . 
Modify Makefile 
bump version to 1 . 8 . 30 
Removed unnecessary return statement 
Revert since it breaks a unit test 
added Esperanto translation for Khmer . 
add rm 
added missing def 
Remove jre6 support . 
added missing semi - colon . 
update README . md for version 0 . 1 . 3 
Add scatter plot of the two_spiral dataset for illustration . 
Turned autoJoin to false to trigger the audio pre - flight checklist 
Ignoring proguard errors from xstream 
removed unused image 
disable broken inspection by default 
remove unnecessary prop 
Reset scroll position when clear state 
ignore Update ' modules / apps / web - experience / journal / . 
Removed unused configuration string 
ignore Update ' modules / apps / web - experience / asset / . 
Add PSD for GreenDroid - GoogleAPIs 
explicitly declaring the Locale of JavaDoc task as en_US 
Move web - sized icon to art / 
Added LLVM bindings for PassManagerBuilder ( Mac OS X binaries ) . 
should run oncomplete function when error , stop tasks and remove surfaceview 
Added missing gen folder 
Updated upgrading section 
Add image of ADM 
correctly handle several class filters remove 
release 2 . 1M4 
Remove new line at end of file 
Exclude JMH tests from coverage reports . 
Add ICU as a java library for docs . 
ignore * . 
remove debug output 
Updating the index file for design proposals 
Bump up pegasus version to 5 . 0 . 12 
Renamed maven assembly to jmxtrans - all . jar . 
Modify install_mongodb . 
Fix Spark version in README ( HADOOP - 275 ) . 
removing MMultApp jars from repository 
Even less debug info . 
Improve comment . 
ignore Update ' modules / apps / foundation / hello - soy / . 
ignore Update ' modules / apps / web - experience / portlet - configuration / . 
Using the latest buildtools version here too 
ignore Update ' modules / apps / collaboration / message - boards / . 
ignore Update ' modules / apps / web - experience / layout / . 
LPS - 45009 Fix tests - > Update the jar . 
Add extension to README file . 
tip updated ( IDEA - 78127 ) 
add npm lint task to gradle 
Bumping rest - client . 
ignore Update ' modules / apps / foundation / portal / . 
update joda - time to 2 . 0 
ignore Update ' modules / apps / foundation / portal - settings / . 
Updated comparison image link 
Add StoreListing 
ignore Update ' modules / apps / web - experience / export - import / . 
update sparc jars 
LRQA - 28693 Ivy needs mirrors - get 
bumping persistit dependency to 3 . 3 . 0 
Even less debug info . 
prepare release storm - hbase - 0 . 1 . 2 
ignore Update ' modules / apps / foundation / expando / . 
Push version to 13 - beta3 , 11242 . 
auto synchronize rng 
Fix # 125 
ignore Update ' modules / apps / web - experience / product - navigation / . 
handle returning from camera without picture 
update msn lib 
fixed NPE in Box . extendToEncompass , close # 1783 
Remove double up unregistering mPackageBroadcastReceiver 
added print stack trace 
Create PULL_REQUEST_TEMPLATE . 
add API reference docs filtering for level 20 
update build . gradle 
update favicon 
add STORM - 1450 to changelog 
Add credentials for CI snapshot deployments . 
fix lost p . __toCharArray ( pathData ) ; 
PY - 1065 Reformat and auto - import do not respect space - after - comma preference in multiline imports 
Added support for automatic legend generation for Wheelchair renderer 
add 1 . 10 . 4 to CHANGELOG 
fixed license 
Updates post 0 . 9 - rc - 3 
Updated changelog 
Updated test for GROOVY - 3401 with a correct example showing that we can put a blankline before the colon 
LPS - 52093 moves icon 
add style images 
Added STORM - 820 to Changelog 
fixed extra document changed event 
Added STORM - 1473 to Changelog 
ignore Update ' modules / apps / web - experience / journal / . 
use smaller interrupt chunk icon 
SONAR - 5718 Fix infinite scrolling in FF 
Removed last trace of Wildfire . . . . . 
Modify Makefile 
Fix JS error stacktraces on Android 
set animation to null when clear animation 
Updated ic_sysbar menu asset 
Properly stop server . 
Remove unnecessary code 
Add a grey line to the top of the search plate image so it doesn ' t 
Add a new ' pre - checkin ' target to help keep checkins clean . 
remove component ' s events when dealloc is called . " 
change default markdown rendering to not use hard wrap 
Updated the index to include AWS related info . 
ignore Update ' modules / apps / foundation / portal - security / . 
Updating Alloy to rev . 74879 
Add * . 
ignore portal - profile 1 . 0 . 0 prep next 
upgraded gradle to 2 . 8 
added OnionKit library import 
Renamed test process to make the test run on case sensitive operating systems 
upgraded proguard to 5 . 2 
Use slack notifications instead of campfire for travis - ci . 
Fix permissions 
Set current version to 0 . 1 . 0 
ignore Update ' modules / apps / foundation / portal - configuration / . 
Allow MapKitView to deal with orientation changes 
LPS - 48469 add contextName to the interface 
setting version to 1 . 0 . 88 
Rewording 1 . 1 . 0 release notes in CHANGES . md 
Turn off fixed rate scheduling in OpenGL 
remove dead code . 
redundant write action 
LPS - 40766 - Remove alloy - 2 . 0 . 0pr7 . zip 
Slightly modified gitignore . 
making the archflags blank 
Add Readme file 
Removed tag roboguice - 2 . 0 - RC2b 
added support for AssertStatement 
bump version for nondex - maven - plugin to 1 . 1 . 1 ( # 3439 ) 
LPS - 35153 - Remove unnecessary CSS 
disposing tree builder 
Update build tools version 
Changed dependencies back to SNAPSHOT versions after tagging 
Add blueprints - core - 2 . 2 . 0 - java5 . jar 
Adds settings icon 
Include strings . h instead of string . h for the strcasecmp prototype . 
fixed compilation issue 
ignore Update ' modules / apps / collaboration / directory / . 
add editor dependency in settings . gradle 
Make argument of NullType constructor nullable 
Added OGNL expression object graph expression language jar 
Updated FML 
update README . md for version 0 . 1 . 3 
Fixed Javadocs in LocalSession . 
make constructor call explicit 
LPS - 47045 Add @ Override 
Disable non - working test . 
update windwos bullet natives ( 32bit ) 
Raise toolchain version 
Only CI build the master branch 
Rename COPYING file to LICENSE 
ignore Update ' modules / apps / web - experience / site / . 
Learned some new structs from Blizzard ' s Hearthstone 
ignore Update ' modules / apps / web - experience / product - navigation / . 
ignore Update ' modules / apps / foundation / portal - configuration / . 
Push version to 11244 . 
build tweaks - see email 
Fix CHANGES . txt for 3 . 0 . 1 
Remove unused background drawable . 
ignore iml files 
update pom . xml 
Set gradle version to 2 . 2 . 1 for compatibility with Nebula NetflixOSS 
FredrichO - fixed spacing on the bottom of the number of columns in the media gallery settings layout . 
Add circle . yml 
Added comments to lazily initialized singleton implementation . 
fix merge problem 
Added ignored_columns . 
prepare release curator - x - zkclient - bridge - 3 . 0 . 0 
ignore Update ' modules / apps / foundation / hello - soy / . 
Bump SpongeCommon for various updates and fixes . 
remove mention of GROOVY - 6226 ( Configure Eclipse Plugin ) now that the issue is closed 
fixing missing types in capture method 
Added bubblechart screenshot . 
Add an ensureOpen check to Publication . hasBeenConnected ( ) . 
updating reference for release 99 
ignore Update ' modules / apps / web - experience / journal / . 
Fixing license header in com . phonegap . api . PluginManager 
Suppress incorrect warning 
Remove provided scope of support lib dependency in pom . xml . 
LPS - 50254 redo sdk to have better logging 
Excel import sometimes drops last row of data . 
Should not be closing system dialogs when Recents is hidden . 
update demo 
setting version to 1 . 0 . 71 
Includes the NOTICE file in the release 
die extra plugins 
Move DeepLearning . java to h2o - algos . 
prepare release checkstyle - 6 . 16 . 1 
changed Agrona dependency to be 0 . 1 to pull from maven when needed . 
Remove overdue . xml config from default killbill start script 
Revert eclipse project specific setting 
Updated imports . 
Updated reference to library to fix problems in login view when fixing typos in URL path 
Change jdk from 6 to 7 in . 
Add runner script for python unit tests . 
add info about " Android - AppMsg - Gradle - Sample " in README . md 
Fix broken link to userimpersonation . html 
Updated the CHANGELOG 
ReadonlyStatusHandler should show a confirmation dialog by default . 
update version of build tools 
add assets link 
ignore Update ' modules / apps / screens / . 
Still having problems with version - updated to a new one . 
Use PApplet . exit ( ) instead of System . exit ( 0 ) for present mode stop button 
Return an empty PluginList instead of null for the 
ignored a few more IDEA files 
Prepare 0 . 4 . 0 release 
Prepare next release v0 . 87 . 5 - SNAPSHOT 
Change the ignore file . 
Fix bad merge of tools version . 
explicitly declaring the Locale of JavaDoc task as en_US 
Remove the launcher filter from the AndroidManifest as per # 57 
Corrected junit jar 
Fix build 
Ignore gradle related files . 
ClearScrollRequest should set a type parameter 
updates ASM to 5 . 1 ( IDEA - 154513 ) 
Fix # 1173 
LPS - 65477 prep next , use latest 
damn optimize imports on commit 
fix a grammatical error in README 
prepare release storm - hbase - 0 . 1 . 2 
prepare release 0 . 8 . 9 
Remove unused file 
added ISchemableSpout interface 
Updated Heroku java version . 
bump version 
ignore Update ' modules / apps / web - experience / layout / . 
Remove inspektr dependency version number since it ' s defined in parent POM . 
Fix spelling in readme 
Fix typo in JDK apt - get line in install . md 
Fixing broken dropdown asset 
updated recovery . zip with better error handling 
LPS - 50254 redo sdk to have better logging 
Fix setName use - after - free 
ignore Update ' modules / apps / collaboration / flags / . 
Added some trace to test . 
fixed compilation error 
activate connections tab when new connection is opened 
Added the shutdown command to the service provider 
Bump version number 
ignore Update ' modules / apps / collaboration / wiki / . 
ignore Update ' modules / apps / foundation / login / . 
r / m obsolete and unnecessary rpc_timeout_in_ms override from test config 
Release the version 1 . 3 . 0 
Implemented getOpacity 
Increase the volume of the AudioTrack instance used for the speech synthesis . 
ignore Update ' modules / apps / foundation / contacts / . 
ignore Update ' modules / apps / collaboration / image - uploader / . 
update location module 
Remove impute . flow from index . list 
try it at a one - liner 
changed minSdkVersion to 8 
adding logo 
ignore Update ' modules / apps / collaboration / announcements / . 
ignore Update ' modules / apps / foundation / portal / . 
ignore Update ' modules / apps / sync / . 
changed maven repository to jcenter 
ignore Update ' modules / apps / web - experience / asset / . 
ignore Update ' modules / apps / foundation / portal - security / . 
Add lineDashOffset to externs for CanvasRenderingContext2D . 
ignore Update ' modules / apps / web - experience / asset / . 
Invalidate ActionMode content rect on scroll . 
Fix the issue of new call failing in 3 - way call scenario . 
ignore Update ' modules / apps / web - experience / product - navigation / . 
Added relative path to the parent POM so that the user won ' t need to 
Update changes log 
Added screenshot 
Bump version number 
Updated changelog 
Corrected typos 
Move tests to elasticsearch test framework 
ignore Update ' modules / apps / collaboration / blogs / . 
updated libs 
updated ios natives 
excluded IntelliJ module library files . 
ignore Update ' modules / apps / collaboration / wiki / . 
add symbolic link from sonar - web to core . properties 
ignore Update ' modules / apps / web - experience / staging / . 
Changed the more info link to point to the wiki . 
Add Powerrr to the list of CONTRIBUTORS . 
Added 2 . 4 . 5 release jar 
Add pbethe @ to bazel CONTRIBUTORS . 
New clean build script 
LPS - 47071 Missed one 
Renaming FrameDebugExtension to FrameCaptureExtension to better reflect usage 
ignore Update ' modules / apps / foundation / portal - search / . 
ignore Update ' modules / apps / web - experience / application - list / . 
Revert " Bump science to pants . pex 0 . 0 . 5 to pick up scalastyle and a fix for the publish task . " 
ignore Update ' modules / apps / web - experience / iframe / . 
Updated documentation index 
Rogue line number for try / catch statement confuses IDE debuggers 
SQLUtils surpport ODPS 
Revert " Upgrade to Flow 0 . 3 . 32 " 
Set anchors for each section in Groovy Ascii docs 
updated magnifier . png image 
Make RUnit NOPASS until further discussion of behavior change . 
Updated Recent Changes doc for H2O - Dev build 0 . 1 . 26 . 1032 
ignore Update ' modules / apps / collaboration / image - uploader / . 
Removed package 
remove a wrong char " 7 " 
Updated changelog 
ignore Update ' modules / apps / web - experience / asset / . 
prepared for next development iteration 
Changed Ignore 
Use a different linker arg on windows sample 
Fix critical dupe bug in AWB 
ignore Update ' modules / apps / web - experience / nested - portlets / . 
Suppress lint errors 
Fix ApplicationInfo copy ctor 
Add logging of Bintray user for CI 
SQLUtils surpport ODPS 
update changelog 
Add a shouldUpdate property to nodes whose layout changed 
ignore Update ' modules / apps / collaboration / bookmarks / . 
updated hibernate - annotations to 3 . 2 . 1 . 
actually run all the tests 
EGL14 . eglCreateWindowSurface should set producerControlledByApp 
turn off verbose logging 
setting version to 1 . 0 . 71 
Use gradle dynamic versioning for dnsjava 
Added Simple Scala Config wrapper 
prepare release HdrHistogram - 1 . 0 . 7 
Create README - ZH . 
Move worldedit . properties to defaults folder so it extracts properly 
LPS - 66848 Add missing Gitignore 
Remove post tag in circle file to attempt build fix 
Fixed path of library in example project . 
LPS - 45043 Remove unthrown exception 
Ignore the client / shade / dependency - reduced - pom . 
ignore Update ' modules / apps / collaboration / item - selector / . 
OF - 919 Update bundled jDTS driver to 1 . 3 . 1 
update changelog for STORM - 330 
use underlying type for builtins 
ZEPPELIN - 852 fixed the fields float outside the box . 
Remove unused import in BufferUtils 
bump engine . io - client 
only run Layout - test & Layout - consts - test 
fixed typo 
Fix ClipboardManager # hasText 
Just to get correct commit rights on buildbox 
Updated small screenshot size 
ignore Update ' modules / apps / foundation / users - admin / . 
Fix bad merge of tools version . 
Changed field type of username in jiveGroupUser . 
Add scala back 
LPS - 61001 Move java file 
LPS - 63116 add lang props 
Add Retina icon for Terminal view . 
Reset postsShouldRefresh 
help topic ( PY - 348 ) 
Freshen screen shots in help screens 
updated ChangeLog 
Fix indentation and code style 
update location module 
WCM - 627 prep next , use latest 
eliminate unused rpubsEnable function 
Specify thread stack size for tests 
Bump version to 1 . 1 . 0 - SNAPSHOT 
Set jdiff version 
Change the default compilation database format to clang . 
ignore * . 
ignore Update ' modules / apps / collaboration / microblogs / . 
removed com . eclipsesource . json from Import - Packages 
The / green command should now only affect dirt on the top layer . 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
Tweak Android setup screenshot 
Make b1 , b2 , b3 my default run configuration . 
Prepare version 23 - beta5 . 
Bump maven lib version to 1 . 0 . 1 . 
update gradle to 2 . 1 . 2 
LRQA - 17280 - Remove extra line break . 
update msn lib 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Remove empty file 
Updated BP libs to latest version 
Create README - ZH . 
Removed requestLayout call since it ' s run via DynamicHeightTextView 
Change javax . servlet to ' provided ' 
Updating Alloy to 40fbe87 ; LPS - 32570 
fix a 9 . png file 
bump up 1 . 1 . 0 
Fixes missing img . 
ignore Update ' modules / apps / foundation / server / . 
Add demo gif 
ignore Update ' modules / apps / web - experience / iframe / . 
Add DestroysInstance to Binding . unbind ( ) 
Add depart icon in itinerary step row 
Travis does not support a JDK named ' openjdk8 ' 
Updated gradle from 0 . 6 to 0 . 7 
Fix online version Py booklet 
Run the tests in parallel . 
Build lint jar targetting Java 7 VMs . 
adding build on jdk8 to travis 
Push version to 15 . 0 . 5 , 15007 . 
rolled back to 0 version 
ignore Update ' modules / apps / web - experience / asset / . 
LPS - 25263 Forgot a property 
ignore Update ' modules / apps / collaboration / flags / . 
If ExceptionsManager . handleException throws , throw the original error 
Removing j2objc - framework dependency 
update readme 
Updated changelog 
prevent read / write after close 
testing out travis as ci 
LPS - 68306 Add new marker file to registry - api 
LPS - 32257 Removed conflicting nekohtml classes 
LPS - 65283 update jar 
ignore Update ' modules / apps / web - experience / journal / . 
Added STORM - 787 to changelog 
Add a little more transparency to widget backgrounds . 
ignore Update ' modules / apps / foundation / portal - settings / . 
add HDFS - 7419 
Fix export on ` LdapComponent ` 
Replace image for layout practice 5 
Changed build tools version to 23 . 0 . 3 , don ' t use rc version 
Require Maven 3 . 0 . 
Fixing special handling of presence type in the model 
remove junit as compile time dependency 
Add a recent change 
Learned some new structs from Blizzard ' s Hearthstone 
Add sleep to rule out false positives in integrationTest 
build number 9 
Updated android gradle plugin version 
formatting readme markdown 
Don ' t schedule script execution on the main thread 
bump version to 1 . 5 . 0 
remove extra - from maven arg 
LPS - 63528 ( WEB ) Move icon files 
fixed reference to ActorSerializer 
Create kk 
FastArray doesn ' t overwrite toString ( ) method 
updated h2o data sheet 
LPS - 48650 rename it only 
ignore Update ' modules / apps / foundation / contacts / . 
Rename README - ZH . 
adding activiti - cdi to deploy profile in current trunk 
Fix vertival resize in terminal ( IDEA - 128769 , IDEA - 126617 ) . 
adding exceptions 
Fixed issue with JUnit @ Category and JDK8 
No longer skip integration tests on Jenkins 
ignore Update ' modules / apps / foundation / portal / . 
Removed a sysout I missed . 
LRQA - 25549 prep next , use latest 
Delete demo . gif 
Catch NameNotFoundException ( support info ) 
Upgraded maven - release - plugin to version 2 . 1 . 
Request now generates strict json code . 
removed try catch block for document . hasFocus 
updated travis setting 
Added another useful thing to capture . 
Built snapshot JAR 
Change maven prerequisite to 3 . 0 . 4 to match the maven api version 
Inflate my ego ( add Aphoh to the contributors list in README . md 
Fix a test not marked @ Test 
Unpack localization during prepare - package phase 
require OS X 10 . 8 . 5 , like we say in the Wiki 
update JIRA url . 
Deprecating ExternalResources . 
Fixed typo for NETHER_WARTS 
added stub for getting buffer from surface texture 
add newest version of cpptasks 
Reverted pom to r2 since our build server can ' t handle r3 
Fix IntentPickerSheetView example wrong syntax 
Added new ask attribute to Item and new " remove " subscription to Item . 
ignore Update ' modules / apps / web - experience / staging / . 
Create README . md 
add also minimum master nodes to the config tempalte 
update HttpUtils 
ignore Update ' modules / apps / collaboration / document - library / . 
Ant build improvements 
add image for layout - gravity 
don ' t set RLIMIT on windoze , either . 
ignore Update ' modules / apps / foundation / portal - lock / . 
Remove ' subprojects / * / ide ' entry from . 
Create README . md 
Fixing the package name 
ignore Update ' modules / apps / web - experience / asset / . 
setting version to 1 . 0 . 71 
Engines should have a block name 
remove boost iostreams include from FilePath . hpp 
bump version 
Fixed version . 
Reverted pom to r2 since our build server can ' t handle r3 
add commons / build 
Replace deleted flash files 
fixed file name of travis script 
Still return a package suspsended dialog if there is no owner . 
Adding constant to PokeGO 
Updating Alloy to rev . 74879 
remove debug output 
Fixed wrong property name 
updated version 
Added build_tmp to . 
Git hygiene 
fix ignore file 
ignore Update ' modules / apps / foundation / map / . 
LPS - 62570 win x64 3 . 3 . 6 lib 
ignore Update ' modules / apps / foundation / contacts / . 
ignore Update ' modules / apps / web - experience / asset / . 
Add HiveType . toString ( ) 
added libsox - dev to apt - get install line in order to resolve all dependencies 
ignore Update ' modules / apps / web - experience / layout / . 
missing from last commit 
LPS - 24377 Explicitly set contribution and participation values to 0 when they are not defined in xml 
Added auto - config for ScriptEngine under Java6 
revert icon to old one 
Removing travis configuration as builds run on Snap ! 
ignore Update ' modules / apps / collaboration / message - boards / . 
Bump SpongeCommon for various updates and fixes . 
Upgraded jackson to 1 . 7 . 4 as well 
update to latest gradle plugin 
Added ShadowRemoteCallbackList . class to Robolectric . java 
Fix # 183 - update screenshots 
Reflect linux native binaries to latest changes . 
Remove OSAtomic header from JreEmulation . h . 
Put @ ViewDebug . 
add new default material images 
adding exception 
ignore Update ' modules / apps / foundation / portal / . 
Add getChildCount ( ) to PShape reference 
Added bottom padding in textview ' s focused rectangle 
add apk demo 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
Travis will update the Slack room # nokogiri - core 
Updating Alloy to 40fbe87 ; LPS - 32570 
fixing documentation 
Fix broken import . 
add ' appendable ' to dictionary 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
Adds screenshots 
RubyDebuggerProxy can both emulate catchpoint removal and use support provided by ruby - debug - ide 
updated TODO 
lighten color in type column 
do not leak menu - > root_panel - > . 
ignore Update ' modules / apps / foundation / frontend - theme / . 
added ForbidAnnotationElementValueCheck 
ignore dist directory 
ignore Update ' modules / apps / collaboration / document - library / . 
Updated FML 
Updated CHANGES 
Decreasing default max connections per node to 10 
added / docs / eggs to gitignore 
Added inspection of running services 
ignore Update ' modules / apps / web - experience / site / . 
LPS - 28250 BaseAsyncDestination should shutdown attach ThreadPoolExecutor on close 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
Ease type png . 
ignore Update ' modules / apps / foundation / users - admin / . 
Supporting API changes in Django 1 . 10 
Removed new lines 
Updated the binaries . 
replace the callback flow graph of FileDownloadListener , add the ' error ' method callback after occuring an exception in ' blockComplete ' 
Remove an unnecessary semicolon . 
Prevent infinite loop on exception 
Reordering the build repositories in the hope that this fixes the jenkins build . 
fixed reference to ActorSerializer 
Hide field packer . 
Fix NPE in PackageParser 
add missing import . 
Add eclipse plugin . 
Preparing WIP - Release v0 . 1 . 43 - alpha 
ignore Update ' modules / apps / foundation / roles / . 
update changelog 
Fix returning wrong field 
ignore Update ' modules / apps / web - experience / product - navigation / . 
Corrected license identifying information . 
Updates build tools . 
GRAILS - 6047 , GRAILS - 6089 - improve handling of calls to local closures in Bootstrap 
Don ' t include all of the user guide src as input files to the task that transforms the assembled dsl reference 
added war / to gitignore of template 
update multiwords . txt 
moving logo to wiki 
Updated reference to library to fix problems in login view when fixing typos in URL path 
ignore Update ' modules / apps / foundation / roles / . 
Add JVM settings in gradle . properties 
ignore Update ' modules / apps / web - experience / site / . 
ignore Update ' modules / apps / foundation / petra / . 
fixed pycharm edu installer artwork 
Add missing curly brace in the README 
remove blade - sample 
Fixed UIExplorerStateTitleMap . js being . 
Ignore lint warnings for unregistered activities 
updated changelog 
enable autoversioning of our submodules 
Fix param for Metrics Consumers 
ignore Update ' modules / apps / collaboration / blogs / . 
improved ' Find in Files ' perf 
setting version to 1 . 0 . 63 - SNAPSHOT 
Added invalidateMaster method to control that behaviour from outside 
do not use Sun ' s internal NotImplementedException , use the standard UnsupportedOperationException instead 
Added travis - ci 
Make bower non - interactive . 
Updated changelog 
ignore Update ' modules / apps / foundation / frontend - editor / . 
update travis config 
replace app_konference . 
add the snapshot of demo project 
fixed accidental suppressing of errors in unit tests 
added shebang line 
Remove jslayoutjs annotation . 
Fix bbb - record - - republish 
ignore Update ' modules / apps / collaboration / flags / . 
Fixed misc problems caused by the renaming / move of BSON classes . 
ignore Update ' modules / apps / foundation / portal - configuration / . 
Groovy Console - - Option to Auto - Save on Run - added missing action mapping entry 
Remove deprecated constant 
ignore Update ' modules / apps / web - experience / product - navigation / . 
add STORM - 1713 to CHANGELOG . md 
Reverted pom to r2 since our build server can ' t handle r3 
Updated README 
Hebrew uses language code iw apparently . 
Don ' t performSend ( ) on onSave ( ) . 
Updated ignore file 
die extra plugins 
Fixing phpunit invocation 
Stupid Windows committed a case - insensitive library reference to GreenDroid . 
FredrichO - set the title of the media activity in the action bar 
Push version to 239 . 
Fix broken test . 
set cam quality to 100 . 
add nuwa image 
Add _site dir to . 
bump version 
Make this library use immutables . 
Upgraded maven - release - plugin to version 2 . 1 . 
adding intellij generated files to . 
removed some compiler warnings 
Set no - op install phase for Shippable CI build 
ignore Update ' modules / apps / foundation / portal - cache / . 
Added banner file for README . md 
removed music . ogg from pax 
improved ' Find in Files ' perf 
add lang - javascript module 
remove allocation tracking file from repo - also add caputures directory 
Adding image folder for Flow documentation graphics 
fix messagespread route # NO_ISSUE 
Updated changelog 
turn off verbose logging 
raise version 
Move local_mapred_error_cache . 
ignore Update ' modules / apps / collaboration / recent - documents / . 
Fixed typo 
Remove redundant onPause from ReaderWebView when hiding view 
updated introduction course 
Removed unused import . 
Override bootstrap ' s th styles . 
Updated changelog 
Add vcs root 
Not using any more 
removing a file from example data that ' s not needed 
Allow Exceptions to propagate out of fold tasks CLJ - 1058 
Add final modifier to ShortcutBadger class to avoid anybody to extend it 
Fix highlight result checkbox position on old FF 
add analysis - kuromoji module 
Create Jar artifact with test code 
update location module 
missing header for linux 
Listen on all IPv6 interfaces 
add LGPL desgination to hunspell 
Added travis 
Correctly initialize animator asynchronousity 
Prepared 2 . 0 . 9 release 
Added Gradle Wrapper Jar 
Prepare library for release 2 . 3 . 1 
Fix signing fallback . 
fix typo in install - packages for win os 
Added e - mail to travis . yml 
temporary reverted changes in javac2 
simplified R install instructions to reflect current config 
setting version to 1 . 0 . 71 
Fixing the package name 
Build fix for change in skia headers 
Remove failed test to troubleshoot 
Removed unnecessary dropdown icon 
corrected pt_BR directory name 
missing vertArray declaration 
Fix permissions 
added travis - ci config 
Move GenericKmlBikeRentalSource to correct place . 
Fix list navigation callbacks for ActionBarView 
Using released version of jetty - enforcer - rules 
Fix routing tests 
Temporarily exclude parquet dependency , due to size , until it ' s needed 
enable memory access protection on solaris 
updated ChangeLog 
Add back underFSStorage into gitignore , which is the default ufs dir for local fs 
Downgrading server to jersey 1 . 3 due to issue with loading of external jax - rs packages . 
ignore Update ' modules / apps / foundation / petra / . 
Added onSnapshotCreated method 
should fix build . 
Updated changelog 
LPS - 11560 Asset publisher displays comments by default 
Added idea output directory to . 
Use new JAR 
Changed location of section for better look ` n ` feel 
Fix param for Metrics Consumers 
add missing period to save as extension 
Bumped minSdkVersion 
add STORM - 1467 to changelog 
cleaned pom 
ignore Update ' modules / apps / web - experience / site / . 
Bump SpongeCommon for various updates and fixes . 
Include server examples in the build . 
update CHANGES 
LPS - 56783 move DDLConstants to api module 
Added auto unit testing 
raise version 
Add STORM - 1245 to changeling 
added stub for getting buffer from surface texture 
Remove unused config fields . 
enable unit test on jdk6 and 7 , and use mvn clean package instead of mvn test - B 
Built snapshot 
CHANGELOG updates and Gremlin 1 . 2 logo added - - - 1 . 2 release in 1 week . 
tries a rescue of my git repository after a network loss 
Add resize to the support library makefile . 
add in missing module traceback 
added readme 
update readme 
Try and handle " death on startup " a bit cleaner 
deleted android_bluetooth_ScoSocket . cpp from makefile 
ignore Update ' modules / apps / foundation / frontend - editor / . 
add uaa classpath to eclipse classpath 
add modules directory 
Updated build configuration to version 3 . 2 . 0 - SNAPSHOT 
Fix bug # 12422326 Unable to change text direction programmatically using setTextDirection Android SDK API - DO NOT MERGE 
post - release add - SNAPSHOT 
Add Travis - CI YAML file - # 722 
Fixed typo in check . nginx 
Removed spurious import of a com . sun class 
SONAR - 3429 In rule descriptions , " < p > " should have vertical spacing 
Remove jre6 support . 
Added ' abc ' to stdlib packages list ( PY - 5935 ) 
add eclipse project dot files to . 
tweak anchor 
LPS - 41254 Only use Validator . isNull for String ( or sometimes Long ) 
Minor optimisation - remove unnecessary call . 
add abortOnError false - so that clean build runs without a problem 
Updated reference to library to fix problems in login view when fixing typos in URL path 
Remove javaVersion task from gradle script 
Remove Eclipse Project Name customization 
add context accessor for subclasses 
Close the message logger so that the file is closed on windows 
updated support JAR 
Fix stupid copy / paste typo . 
removing comm files from jre since they needn ' t be in there 
Suppress UnsatisfiedLinkError ( debug info ) 
Should not use arbitrary string as printf format . 
ignore Update ' modules / apps / foundation / portal - scheduler / . 
ignore Update ' modules / apps / web - experience / journal / . 
Prevent new ripples when max reached 
Removed redundant line from README . md . 
LPS - 48539 Move TransactionalTestRule to portal - test 
Fix REST test delete / 42_missing_parent to catch a RoutingMissingException 
Preparing for release 3 . 3 . 0 
added webapp ui test bundle 
update readme 
ignore Update ' modules / apps / web - experience / layout / . 
removing unnecessary support extra for Travis 
Updated support library 
LPS - 66923 Migrate packageinfo 
Updated changelog 
accessing wrong var 
upgraded netty 4 . 1 . 2 
ignore Update ' modules / apps / foundation / xstream / . 
ignore Update ' modules / apps / foundation / portal - template / . 
LEP - 6055 - " Add Application " infinite loading 
Create README . md 
fixing Junit dep scope to test 
Fixed Travis configuration ? 
Added lib required for smartcard support 
Module does not leak file handles anymore 
Add large suffix . 
Uses device UID or name ( instead of index ) for PortAudio CaptureDeviceInfo locator . 
ignore Update ' modules / apps / foundation / portal - search / . 
adding some more file to ignore 
Fix multi tab support regression 
Fixed tiny initialization issue with FileCopierUnitTest 
reenable daylight saving test , now that we use joda - time 2 
Bump gRPC to version 0 . 9 . 0 
redundant write action 
ignore Update ' modules / apps / collaboration / message - boards / . 
Removed system out . 
Added private constructor . 
adjusting faulty service string 
Revert " Rollback avs to 2 . 9 . 8 ( 2 . 9 . 3 was too far ) " 
Install Kramdown 
remove web 
Write checkstyle to stdout . 
Add a task that resolves all configurations . 
Guarding moved pass CheckRegExp with skipNonTranspilationPasses flag . 
LPS - 46847 - inline editor links should have a cursor pointer 
add support v13 
Changed library URL to a PURL . 
ignore Update ' modules / apps / foundation / portal - settings / . 
set version 
Moved ( copied ) components and ported to kernel / index / shell 1 . 0 - SNAPSHOT . 
Fixes add contact dialog and activating add button . 
LPS - 63528 Duplicate util package , unify under service layer 
Fixed test 
Replace registerForEvent ( ) with equivalent call that makes registerForEvent ( ) unused . 
Upgraded Blueprints embedded libraries 
Updated FML 
Added sample app dashboard screenshot 
Assign newly created stream to field instead of leaking it 
remove unnecessary LINK_FLAGS from consoleio project 
documented socket handler enhancement 
Build X module by default . 
Added target to . 
Fix config option loading for TitanFactory Builder 
don ' t set the application title in the library 
fix broken stream graph range selection 
Update ignore file 
Method doesn ' t throw an exception 
Record correct shell test failure times 
ignore Update ' modules / apps / foundation / users - admin / . 
update screenshot 
Bump SpongeCommon for various updates and fixes . 
LPS - 42815 - Error message style does not wrap around long word without spaces completely in entry preview 
ToggleButton could keep a reference to a previous drawable 
add / target / to . 
Make SwitchPreference switch more Material 
ignore Update ' modules / apps / sync / . 
Repackage samples zip with SampleSyncAdapter and CubeLiveWallpaper . 
Fix travis building . 
Uses device UID or name ( instead of index ) for PortAudio CaptureDeviceInfo locator . 
add new otp logo icons 
regenerate gradle - wrapper . jar with 1 . 9 - rc - 4 
Added STORM - 1213 to Changlog 
Made empty constructor for ModMetadata public 
updated R notebook icon @ kevinushey 
bumped parent version from 2 - SNAPSHOT to 2 
ignore Update ' modules / apps / web - experience / staging / . 
Added support to JML for removeFriend to work . 
ignore Update ' modules / apps / collaboration / image - uploader / . 
ignore Update ' modules / apps / collaboration / announcements / . 
Fix the DroidGap activity Lifecycle broken issue 
Smack 4 . 1 . 5 - SNAPSHOT 
missing import 
Output build details 
gitignore all build / directories 
fix failing test 
rip off jruby ' s travis notification settings 
Ignore mac hidden files for ant auto - complete 
fixed license 
eliminate eclipse warning 
added cython to py requirements 
Bumping version to 1 . 5 . 3 . 
Removed bogus comment from createGraphics . 
prepare release astyanax - 0 . 8 . 10 - SNAPSHOT 
ignore Update ' modules / apps / foundation / portal / . 
Fix build . 
ignore Update ' modules / apps / collaboration / recent - documents / . 
Do not call stop ( ) on the MediaSource if it hasn ' t been started . 
removed llvm dependency for device . 
Disabling test directory as slave not able to access hdfs 
ignore Update ' modules / apps / collaboration / notifications / . 
consume the data 
updated pac4j version to the released 1 . 8 . 2 
Use local installed pybabel and i18next - conv 
update screenshot 
Properly remove GhostViews when Activity Transition canceled . 
added hardcoded fml version file 
Only show scrollbars in action menu on overflow 
ignore Update ' modules / apps / foundation / frontend - js / . 
ignore Update ' modules / apps / foundation / portal - security / . 
remove x attribute of java file 
Rebuilds the Windows x64 binary of the PortAudio support from its latest source / r7982 . 
Removed un - used p . paused ( ) . 
update osx bullet natives 
Fixed test 
updated gradle wrapper to 1 . 10 
ignore Update ' modules / apps / marketplace / . 
added travis ci config 
Fix monochromacy simulation 
Updating Alloy to rev . 74879 
bump version 
make default value of N_INSTANCE_BEG and N_INSTANCE_END the same as stated in README 
Remove unused imports 
Added relative path to the parent POM so that the user won ' t need to 
citibike small runit passes with spencers fix 
Revert JDK8 travis change ( seem to be failing ) 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Cancel the date picker dialog when BUTTON_NEGATIVE is clicked 
Fix warning 
added support for GvTags 
Fix ` maven_repositories ` section link 
added back in author / revision info 
Renamed file to match class name 
Removed unused library . 
Updated changelog . 
ignore Update ' modules / apps / web - experience / iframe / . 
LPS - 66848 Add missing Gitignore 
updated TODO 
Add scala back 
Updates post 0 . 9 - rc - 3 
Travis needs tools before platform - tools for 24 . 0 . 1 . 
IDEA - 83589 Splitter panel has tabs but no content 
upgraded logback to 1 . 1 . 5 
added CNAME support for gh - pages 
Add support for the Firebird database - Fixed multi - record INSERT 
Add improved libscreencapture JNI for Linux ( 32 / 64 ) prepared by Damian Minkov . 
Remove temporary test 
Customization guide should have correct title . 
add image for transition drawable 
Bump the version number to 2 . 2b3 
Edited audio - test . mp3 to 10 seconds 
Fix BackupManager . isBackupEnabled ( ) 
ignore Update ' modules / apps / marketplace / . 
ignore only certain lib / dir 
give access to the defining classloader 
Changed Spout maven repo to more stable url 
Add missing UNWIND entry ; disables . 
ignore Update ' modules / apps / collaboration / microblogs / . 
Fixed way of marking comments . 
Fix root project name . 
ignore Update ' modules / apps / foundation / petra / . 
remove debug code 
Restore Dexguard obfuscation , re # 301 
Fix build 
Add the Servlet 3 . 0 xsd ' s 
Updated changelog 
ignore Update ' modules / apps / collaboration / document - library / . 
Add permission model - - Adding a newline at the end of FsPermission . java 
ignore Update ' modules / apps / foundation / license - manager / . 
Added missing gen folder 
add groovy property icon 
Changed components to use parent pom v 4 , producing source and javadoc jar packages . 
Reset languageMode to languageIn at the beginning of processNewScript ( ) 
removed sample server config ( irrelevant now ) 
Removed stale proguardAchives configuration . 
Fix bitmap tinting 
Fix screen magnifier scaling due to ScaleGestureDetector changes . 
add DS_Store to gitignore 
 @ Deprecated does not have effect in Groovy 
GrailsBootstrap was setting the pluginSettings property on the plugin 
Fix # 12 
pass the long clickable setting to the underlying control 
LPS - 66431 prep next , use latest 
Prepare next development version . 
Changed screenshot 
Remove an unneeded assignment 
Prepared 2 . 0 . 8 release 
update emitter version 
Adding 2 . 4 . 7 jar 
Updated BP libs 
ignore Update ' modules / apps / foundation / login / . 
Fix osmand key location 
Add dependency - reduced - pom . xml in . 
add osm module to parent pom 
removed erroneous tab character 
add gitkeep for assets 
LPS - 61001 Move java file 
cleaned pom 
Added STORM - 1837 to Changelog 
LRQA - 25160 prep next , use latest 
remove bogus unreferenced classpathref ( cut and paste error ) 
added a dummy test case 
ignore Update ' modules / apps / foundation / portal - configuration / . 
Tried new gititgnore file 
fixed exception in django test runner with custom test_runner function 
update legacy metadata 
Fix the build . 
Add package . html . 
Fix functor removal 
Add splitIndex Javadoc option to the root project 
updated the parent pom version to 4 which enforces you to use maven 2 . 1 or higher 
Added unit test for bracketless else ( humphd ) 
add jamm - 0 . 2 . 5 . 
Bump the version number to 1 . 2 . 8 - dev 
save storage format version after successful cleanup 
Bump k9 
ignore Update ' modules / apps / foundation / frontend - css / . 
Move strong rules memory test to large 
ignore Update ' modules / apps / foundation / frontend - theme / . 
FileSystemCompiler # generateFileNamesFromOptions is adding filenames multiple times 
remove javadoc warning 
Only use TravelAgent if supplied ; Addresses BUKKIT - 3466 
setting version to 1 . 0 . 71 
Wait the end of ICE processing to process session - accept message . 
ignore Update ' modules / apps / web - experience / site / . 
Fix bug 3425610 Adjust Lock sound level 
rename file so its title has a space in it 
Updated changelog 
Ignore mac hidden files for ant auto - complete 
revert version 
missing from last commit 
Make blueprints - test a test scope dependency 
update all modules 
add gitignore 
Gradle should match project . properties after d816483a7cd4d98b5b136139ccaacd322e0ab5b6 
Moving test to no pass as there is already LBFGH 
Move H2OApp into a package 
forgot to commit the services file 
remove vbox / shared directory from . 
Removed un - used p . paused ( ) . 
ignore Update ' modules / apps / collaboration / document - library / . 
Reset build identifier to next milestone snapshot 
Remove image sample 
updated ChangeLog 
Fixed error in example config . yml . 
Only include files that end in . 
Bump dependency on neo4j - browser . 
update Readme . 
Repackage samples zip with SampleSyncAdapter and CubeLiveWallpaper . 
exclude the source jar files . 
update support version to one in travis ci 
gitignore for linux iterate script 
Skip tests for a while 
excluded NightlyTest in the default build profile 
Fix landscape layout of LockScreen on devices with a keyboard 
removing submodule MenuComponent 
fix broken astroboy dep 
Removed Key Value Server from SVN repository . 
Updated version in README 
setting version to 1 . 0 . 69 
Add shell script for zan 
add debian - sid for apt sources to get libunwind8 - dev 
ignore Update ' modules / apps / web - experience / layout / . 
Write checkstyle to stdout . 
remove dependency on react - native which will break the packager 
Updated changelog 
Updated changelog 
Changed the more info link to point to the wiki . 
Rename setup_environment to install_frodo . 
Fix build 
use oracle ' s official jdk 
MinecraftForge / FML @ 5d6dc5dce37e488188d6fc468c16e8a6183a3610 Fix up other exit points . 
Fix block break robots going into sleep mode after successfully harvesting block . 
add usage 
Have project ' s build . gradle look for a build - extras . 
ignore Update ' modules / apps / collaboration / wiki / . 
Changed DBDecoderFactory to interface and added method . 
Push version to 15 . 0 . 5 , 15007 . 
Added intellij generated files 
add a runtime dependency on validation - api 
ignore dist folders 
ignore Update ' modules / apps / web - experience / export - import / . 
Added tag 0 . 0 . 7 . 6 for changeset 45e1e724eee2 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Fix permissions 
ignore Update ' modules / apps / web - experience / trash / . 
Fix bad pixels in the icon 
shift - Enter - > trimToSize rudminentary focused remaining editor , fixed 
Exclude gwt files , so that maven tests can run 
No longer need commons collections . 
Remove unused methods from signature 
Fixed a compilation error ( returning from a void method ) . 
ignore Update ' modules / apps / collaboration / blogs / . 
Updated CHANGES . txt 
updated library 
LPS - 54533 moves icon 
Fix build 
Modified the maximum presentation size from 20mb to 30mb 
Updated build configuration to version 3 . 2 . 0 - SNAPSHOT 
moved doc page to the installation directory 
delete an unused flag in IncrementalIndexSegment 
Upgrade Ivy 2 . 2 . 0 RC to final 
ignore Update ' modules / apps / foundation / expando / . 
ignore Update ' modules / apps / web - experience / export - import / . 
ensure utf8 encoding of javadoc 
update changelog for STORM - 335 
Fix the build . 
Saving Blacklist and Hold for Moderation lists when dismissing dialog 
Updates the SC logo in the top MSI banner . 
ignore Update ' modules / apps / web - experience / iframe / . 
add MavenCentrail ( ) in allprojects of build . gradle 
make THREADS configurable through environment 
hide feedback button in mobile view 
Set VERSION to " dev " on master . 
update msn lib 
Fix SearchView collapse on text input . 
ignore Update ' modules / apps / foundation / portal - lock / . 
LPS - 65920 ( WEB ) Move css files 
ignore Update ' modules / apps / web - experience / asset / . 
LPS - 39662 Add @ Override 
Fix the issue of new call failing in 3 - way call scenario . 
do crlf conversion when core . autocrlf is on only on xml files 
Use correct param for heightMode in RelativeLayout horizontal measure 
Add item click events to change log . 
disable reloading for scripts with dates in the future 
Fix log output on Travis 
Fix permissions 
Upgraded SVNKit to 1 . 2 . 0 so that ReleasePlugin . groovy works with svn 1 . 5 working copies . 
Updated graphdb libs 
Removed tag roboguice - 1 . 1 . 1 
temporarily disable unit test 
ignore IntelliJ project files 
Migrate to container based infrastructure 
Gradle build tools version 1 . 0 . 1 
ignore Update ' modules / apps / sync / . 
adding missing nfc demo png 
start drag of text selection on initial press 
ignore Update ' modules / apps / foundation / frontend - js / . 
setting version to 1 . 0 . 124 - SNAPSHOT 
Fix builder crash # 21 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
use a better icon ( unfortunately , it still doesn ' t get scaled nicely in the download window , at least not on my test on Ubuntu ) 
Move tests to elasticsearch test framework 
Updated CHANGES . txt 
add Change swipe to dismiss color in UpComingChanges 
Changing Honeycomb default wallpaper 
ignore Update ' modules / apps / collaboration / document - library / . 
ignore Update ' modules / apps / foundation / frontend - taglib / . 
ignore Update ' modules / apps / foundation / frontend - theme / . 
typo cont ' d ( remove deprecated method in trunk ) 
set release version 
ignore Update ' modules / apps / web - experience / journal / . 
Remove CCC 
bump to version alpha - 7 
started core project 
Fix issue displaying modals with new gridster 
LPS - 57681 are we upgrading components , or bundles ? 
build linux / i386 against older glibc ( 2 . 3 . 4 ) for compatibility 
LPS - 66483 Disable it 
Make validateConf cmd output to console 
Bump version to 1 . 9 . 42 . 
update todos 
ignore Update ' modules / apps / foundation / portal - instances / . 
Added missing files . 
Add jni project submodule 
bumped parent version from 2 - SNAPSHOT to 2 
deleted unused changelog 
Fix RCTImageLoader ' s priority 
Set oss parent to 9 
Create gradle files to appease NetBeans plugin 
destroy NEWT window on exit 
add missing depency to gradle file 
Fix xhdpi box 
update doc 
Fix android_media_AudioSystem_getMasterMute return type . 
Added repositories to rockerhieu / mvn - repo 
Added Travis 
comment out snapshot plugin for release 
Revert " Android package name requires at least two segments " 
prohibit " Schafmittel " 
Refactored quartz plugin . 
set ulimit 
ignoring eclipse files 
Ignore heap dumps created during profiling ( * . 
Add average current property 
ignore Update ' modules / apps / foundation / portal - settings / . 
Removed unused file 
Made HashJoinTest an integration testcase 
Reenabled deployment of assembly artifacts to fix build for largetests 
Add proguard rule for android . app . Notification 
ignore Update ' modules / apps / collaboration / message - boards / . 
Set keystore for DesktopFilters . 
Fix compile warning 
FredrichO - fixed spacing on the bottom of the number of columns in the media gallery settings layout . 
Added docs for IDE / plug - in 
Updating Alloy to rev . 74879 
fixed bug in edit action of generated controller that was leaving out reference the domain class instance in returned model eg . 
Create README . md 
Updated README . md 
imgur hosted gif 
Delete lvtea0105 
changed license name 
Removed unused library . 
updated api . services . png image to reflect new api structure 
added scripts to create heron - tools self extracting binary 
add the ruby method Snapshot # resource ( alias of Snapshot # project ) 
Delete header . jpg 
added Kasper to list of developers 
ignore Update ' modules / apps / collaboration / bookmarks / . 
fix failing test 
setting version to 1 . 0 . 68 - SNAPSHOT 
Ignored test results from TestNG ( issue # 36 ) . 
Uses device UID or name ( instead of index ) for PortAudio CaptureDeviceInfo locator . 
Write checkstyle to stdout . 
ignore Update ' modules / apps / foundation / frontend - theme / . 
ignore Update ' modules / apps / collaboration / notifications / . 
Fix travis error 
Updating all components to use version 3 of the parent pom . 
ignore Update ' modules / apps / web - experience / layout / . 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
update changelog 
Not using any more 
added ServiceLoader spec for UdcExtensionImpl 
Fix version number 
setting version to 1 . 0 . 74 - SNAPSHOT 
ignore Update ' modules / apps / foundation / frontend - css / . 
Removed unused ic_reader_video_overlay . png asset 
added all the documentation images to the repository . 
Create implicit sort remembering setting2 ( minor indentation error ) 
Improve Systrace support 
meteor / AWSCloudFormation added to validation list 
Removed TODO comment . 
remove use of deprecated property on Test 
Changed standard rrd_storage_path for development env as this may cause frequent problems with missing directories 
Add travis file to continous integration 
Fix fillLiquidContainer - return null , not the empty container for 
Emit better ( correct ) timestamps that respect AAC upsampling . 
added ignored words . 
fixed value type of " private " in package . json 
Add break statement on load extractor from form 
ignore Update ' modules / apps / foundation / portal - search / . 
remove x attribute of java file 
remove customized HelpUI override 
update icons 
ignore Update ' modules / apps / marketplace / . 
Allow null values for json in CollectionMetainfo 
ignore dictionary - web 1 . 0 . 0 prep next 
Updated Flow version 
added travis - ci config 
Reset log level to info 
changed publishJavadoc task from Copy to Sync 
add readme so directory stays live 
Check Mail Icon 
avoid nexus username and password on normal build 
In order to keep sysout clean removed dodgy code 
repackaging guava 
bump to version 5 . 2 
update win32 - x86 native 
update antlr - maven - plugin to release version 2 . 1 
Updated changelog 
Make Wrench full 3D 
Add image for new avd 
prepare release checkstyle - 6 . 11 . 2 
Doesn ' t re - sort app windows when move task to top 
Fixed lost text in notifications for failed uploads 
remove mention of GROOVY - 6226 ( Configure Eclipse Plugin ) now that the issue is closed 
remove useless println 
LPS - 35256 Fix broken test 
ignore Update ' modules / apps / sync / . 
Add the goal ' deploy ' to maven release plugin 
starting 0 . 5 . 4 - SNAPSHOT 
ignore Update ' modules / apps / screens / . 
disable groovyc temporarily 
Add plugins target to Makefile 
add doc / cql3 / CQL . 
Add PageSink to SPI 
Changed components to use parent pom v 4 , producing source and javadoc jar packages . 
Prepare library for development 
Scroll test was missing an index - fails when other indices present 
updated version 
remove tpc / lib / fastjson - 1 . 2 . 10 . 
Add Application class . 
Updated Symbolic Link to CREDITS 
Updated FML 
Add category views image 
Fix null top view crash 
ignore Update ' modules / apps / collaboration / microblogs / . 
Trailing white - space police . 
update ppc64le natives 
ignore Update ' modules / apps / web - experience / export - import / . 
ignore Update ' modules / apps / collaboration / image - uploader / . 
Change repository URL to https . 
ignore Update ' modules / apps / collaboration / flags / . 
fixed logfile name 
Fixed issue with JUnit @ Category and JDK8 
Updated changelog 
Bump version numbers for release of pegasus 1 . 9 . 23 
Upgrade version library to 1 . 1 . 0 
add heap dump on OOM , see # 304 
ignore Update ' modules / apps / web - experience / staging / . 
don ' t clear disk cache on finish 
fixed git ignore name 
Added tag 0 . 0 . 7 . 4 for changeset f415c01ff925 
Updated build . gradle to point to the strangelydim maven repo again for the latest Agrona snapshot jar . 
add STORM - 1466 to changelog 
LPS - 26457 - Fix broken image 
Require gradle plugin 
Delete build . gradle 
Keep it as a test dependencies 
Fix changelog 
added new very spartan control button to controls . png 
updated pdf with latest version 
fix a bad merge 
Add mk to " Shell script " group 
set focus to html preview frame on load 
remove obsolete drawable 
Remove empty file 
updated version 
Call AudioTrack . flush ( ) before AudioTrack . release ( ) . 
remove unneeded build . doLasts for driver . 
Add a record to copyright waivers 
Smack 4 . 1 . 0 - rc2 
CORE - 2136 Mysql must quote PARTITION as a keyword 
fixed heap spec for functional tests 
ignore Update ' modules / apps / foundation / configuration - admin / . 
ignore Update ' modules / apps / foundation / plugins - admin / . 
Updated changelog 
prepare for next development iteration 
LRQA - 18812 Add missing google images pngs 
Gradle required 2048 heap for multidex 
ignore Update ' modules / apps / foundation / frontend - js / . 
LPS - 48469 add contextName to the interface 
Added STORM - 373 to Changelog 
added OracleJDK7 , OpenJDK6 , and OpenJDK7 to Travis CI configuration . 
Updated submodules to latest 
Added build_tmp to . 
ignore Update ' modules / apps / foundation / portal - search / . 
ignore Update ' modules / apps / web - experience / layout / . 
Add ColeMurray to contributors 
add ignore to the libs 
integration tests should use the baseVersion when copying artifacts 
Prepare next release 
ignore Update ' modules / apps / foundation / frontend - editor / . 
add new updated octicons 
Corrected Javadoc on MapReduceOutput 
setting version to 1 . 0 . 71 
Updated changelog 
ignore Update ' modules / apps / web - experience / export - import / . 
Add multinode suite . 
no argument constructor , adjust Javadoc 
Fixed default focused element for credentials dialog opening ( password is focused if username is disabled ) 
Add docs directory to . 
Add cast to EditText to avoid compilation error in README 
Fixed remove webiew bug 
disable groovyc temporarily 
Fix floating point exception in emulator 
ignore Update ' modules / apps / foundation / roles / . 
LPS - 65225 update hash 
add default to debug - mode 
update druid 
Add stacktrace to travis command 
ignore Update ' modules / apps / foundation / frontend - js / . 
Missed import 
ignore Update ' modules / apps / collaboration / bookmarks / . 
Add arabic to the list of translated release notes 
Create gradle files to appease NetBeans plugin 
updated CHANGES . txt 
Putting tests in correct location 
updating changelog 
Upgrade InfluxDB Java Client to support 1 . 0 
Correct a typo . 
udpated the read me 
Don ' t initialize JMF 
Fix a FindBugs warning 
ignore Update ' modules / apps / foundation / portal - search / . 
Solved problem with proguard . cfg 
ignore Update ' modules / apps / collaboration / document - library / . 
Test Fixes - Social Office - dependencies 
ignore Update ' modules / apps / static / osgi / . 
updated wiki snapshot 
Push build . 
ignore Update ' modules / apps / collaboration / microblogs / . 
Reduce the amount of logging from the Javadoc plugin . 
adds a test for # 444 not to regress 
Remove Tween externs . 
Remove trailling comma 
ignore Update ' modules / apps / foundation / map / . 
LRDOCS - 1103 namespace it 
Use 32dp size image for PictureInPictureAction icon 
Always send ESC for backspace 
ignore Update ' modules / apps / foundation / portal - scheduler / . 
Fix React warnings 
add new default material images 
ignore Update ' modules / apps / foundation / hello - world / . 
Require Maven 3 . 0 . 5 to stop users from using insecure 3 . 0 . 4 
Removed print statement which was probably set during debugging 
Add padding to selected table / partition 
ignore Update ' modules / apps / foundation / contacts / . 
add jamm - 0 . 2 . 5 . 
Add demo gif 
Updating Alloy to dcea66d ; LPS - 25276 
should fix the build . 
Remove AppState from Known Issues page 
bump version to r08 - SNAPSHOT 
Remove old listwidget preview image . 
Remove blank line . 
list comp expr has a type 
Removed 2 . 4 . 6 jar 
Add Thumbs . db to gitignore 
adjusting changes . txt 
Commit version 1 . 3 . 1 
Add Mike to pairs file 
remove monitoring dead locks 
Include lib / instead of libs / 
removing tools . jar and moving it inside the jre 
Why didn ' t I just use a . 
Hide field packer . 
Added EnderCrystal entity 
Fix a bug disappearing installerPackageName info of packages after reboot . 
Add lineDashOffset to externs for CanvasRenderingContext2D . 
Fix typo for networkingPrivate . WiMAXStateProperties extern . 
Added STORM - 811 to changelog 
ignore Update ' modules / apps / foundation / login / . 
Make InstallCommand ' s constructor public 
Bumped version to 5 . 0 . 0 - alpha4 
Fix gif encoder application id . 
LPS - 65225 update hash 
ignore eclipse bin directory from git 
ignore Update ' modules / apps / web - experience / export - import / . 
ignore Update ' modules / apps / collaboration / microblogs / . 
update CHANGES 
added indexer . yml to build_release . 
ignore Update ' modules / apps / collaboration / wiki / . 
Add lineDashOffset to externs for CanvasRenderingContext2D . 
ignore Update ' modules / apps / collaboration / blogs / . 
Fixed accidental refresh when sending media file to other app 
removed extraneous whitespace from pull request 
Fixed vararg parser typo . 
bump local threads 
Updated change list 
LRQA - 28741 Set default blacklist property in test . properties 
Remove memory limit due to OOME 
update pom 
added latest groovy jar 
Updating Alloy to rev . 74879 
update to latest android iconics - core 
swapped the spread to the single page edition . 
fixed typeo in test 
Removes an ancient doc file that is today extremely obsolete 
ignore Update ' modules / apps / foundation / frontend - js / . 
Removed not - needed file . 
Add package . html . 
Revert " Reduced header size " 
add jar to libs folder for ant to find . . . 
LRQA - 26503 Use full version number 
added linksource to javadoc so we can navigate from javadoc to source code 
Set minSdkVersion + targetSdkVersion via build . gradle 
removing unimplemented method activeScanSessionUrls from ClientApi 
updated version number 
LRQA - 18719 Add new property ' community . app . acceptance ' 
Added castor properties 
ignore Update ' modules / apps / web - experience / export - import / . 
Exclude rxjava . properties in Android library 
if an error occurs then set in creation to false to prevent repeat execution from hanging 
ignore Update ' modules / apps / foundation / frontend - js / . 
removing duplicated arraycopy ( for arrayCopy ) 
added gitignore to blob 
update changelog 
ignore intelliJ files 
remove useless ` deleteAllAccounts ` in ` initWpDb ` 
Call super . onCreate ( ) 
Updated Ant jar 
Bump SpongeCommon for various updates and fixes . 
Added entry for " Remote Code Execution - CVE - 2012 - 1823 " 
ignore Update ' modules / apps / web - experience / journal / . 
ignore Update ' modules / apps / foundation / frontend - editor / . 
ignore Update ' modules / apps / collaboration / wiki / . 
Added translation using Weblate ( Nepali ) 
ignore Update ' modules / apps / foundation / portal - store / . 
Added missing early_stopping arg from glm r wrapper . 
Remove setting applicationId from library configuration 
JAL 59 - Add new images 
update capture gif 
update icons 
LPS - 15480 Updated alloy - taglib . jar to 76596 , you must run " ant build - alloy - taglib " from trunk using JDK 5 . 
Updating log statement to reflect the correct chmod values 
Updated FML 
Add jacoco_build . 
updated credits 
Fix travis compilation 
LPS - 51079 - Text Box field can hide links and buttons on resize 
Moving PCA golden test to NOPASS until I figure out the source of the numerical inaccuracies . 
ignore Update ' modules / apps / collaboration / document - library / . 
update factory images 
LPS - 55259 - Updating Alloy 3 . 0 . x to 6eb8209f0cdb27ecee0494e1653220159d9d7439 
ignore Update ' modules / apps / foundation / portal - remote / . 
ignore Update ' modules / apps / foundation / portal - search / . 
Set revision 3 . 3 . 5 . 
ignore Update ' modules / apps / collaboration / microblogs / . 
updated distribution . xml to include whirr recipes and configuration files . 
ignore Update ' modules / apps / web - experience / product - navigation / . 
Make the throttling more sensitive to end - to - end latency . 
added linksource to javadoc so we can navigate from javadoc to source code 
SONAR - 5718 Fix infinite scrolling in FF 
Updated changelog 
Added LLVM bindings for PassManagerBuilder ( Mac OS X binaries ) . 
Added multichat operation set definition and Gibberish protocol implementation . 
Bump SpongeCommon for various updates and fixes . 
ignore Update ' modules / apps / foundation / frontend - css / . 
Prepare version 19 - beta2 . 
disable optimizations for interfaces 
Fix a bug disappearing installerPackageName info of packages after reboot . 
Add one - sentence summary to management section 
fix some bug . . . . . . 123 
removed note from Robot1_Draw example 
Added STORM - 1631 to Changelog 
updated jar 
ignore Update ' modules / apps / collaboration / directory / . 
calling superclass on serialization 
ignore Update ' modules / apps / foundation / portal - security / . 
add globus 
changed maxRecordStoreEntries default to 100k 
rename for letter case 
Adding the singleton module 
Bump version to 1 . 0 . 0 - beta . 1 . 
updated studio with Password Validator labels fix 
Added Circle CI configuration 
gh - 471 - updated travis script 
remove component ' s events when dealloc is called . 
update target API 
Fix typo in build file 
Rebuilds jndirectshow . dll with a newer version of mingw64 . 
upgraded guava to 20 
Adding couchbase module 
Added fake large icons 
removed old static html file from git . 
added surround with tests 
Actually store the newly computed deceleration . 
Fixed issue where the " start scan " button would be enabled with no 
update maven - release - plugin to 2 . 5 ( fixes issue where release fails to tag properly ) 
LPS - 69962 Add packageinfo 
ignore Update ' modules / apps / foundation / petra / . 
Delete obsolete icon 
ignore Update ' modules / apps / marketplace / . 
Use local installed pybabel and i18next - conv 
adding " Belarusian " 
add waffle . io badge 
Create TestUtils . java 
Specify version of gpg plugin to use 
Add junit as a dependency for subprojects ( modules ) 
hide description on custom plugin panel 
LPS - 41597 Make the build fail next time 
Ignore Eclipse files 
Added JAVA_8_HOME to required environment variable 
ignore Update ' modules / apps / foundation / portal - search / . 
Bump SpongeCommon for various updates and fixes . 
add # 3479 ( SOURCE and CAPTURE cqlsh commands ) to CHANGES 
Added auto - config for ScriptEngine under Java6 
increased the mvn version to avoid possible build bugs 
Added Ryan as a maintainer since he has done a bunch of work . 
optimized imports 
ignore Update ' modules / apps / foundation / configuration - admin / . 
ignore Update ' modules / apps / collaboration / bookmarks / . 
Updated VERSION . txt for # 353839 . 
add alternative method to create Archive , fix typo 
e9c5ade 46ab5e1 
remove monitoring dead locks 
LPS - 45461 update jars 
using gradle 
Add truth - 0 . 27 . jar to third_party / truth . 
ignore Update ' modules / apps / web - experience / staging / . 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Prepare version 22 . 0 . 0 - beta4 . 
ignore Update ' modules / apps / foundation / contacts / . 
tidied up script 
Remove sleep 3600 . 
Removed unused import 
don ' t stop the file_monitor on process exit ( creates unpredictable wait times - - better to let the OS do the cleanup ) 
ignore Update ' modules / apps / foundation / portal - remote / . 
ignore Update ' modules / apps / collaboration / bookmarks / . 
LPS - 67469 LRDOCS - 2841 remove build . gradle since that project is now empty " 
add button ui to unix 
removing submodule MenuComponent 
Try building and running with JDK 8 
add a - d flag to dpkg 
Return the record state locked 
Added STORM - 1361 to changelog 
Add Eclipse ' s bin / folder to . 
Set bg and fg colour in site . css 
Updated build tools and sdk 
update aboutlibraries 
Removes override notation for getSSLSocketFactory because of signature conflict 
ignore Update ' modules / apps / collaboration / document - library / . 
Use Java 7 on AppVeyor 
Removed some whitespace in docs . 
Fix setName use - after - free 
ignore Update ' modules / apps / collaboration / wiki / . 
Updated hbase datastore to implement interface 
Fix typo on build_release 
ignore Update ' modules / apps / foundation / portal - scripting / . 
Ignore eclipse generated markdown files 
removed junit from test folder because junit is now runtime dependency 
updated ChangeLog 
Delete default README 
use the latest one 
Fix build error on linux 
SONAR - 4636 Bind handling of branding resources to a later phase of the build 
Prepare version 28 - beta3 . 
add intelliJ files to gitignore 
missing return in svg ' s getCoords 
Added missing gen folder 
reset inspektr version back to the GA released version 
Ignored rrd directory that someone keeps creating for me 
update win64 natives 
Fix typo in AbstractTestQueries 
Updates minify enabled true for release builds . 
Updated parent version . 
LPS - 69878 Set the new column to null 
add libffi to yum dependencies 
bump engine . io - client 
Upgraded version in etc / pom . 
update sparc natives 
Log internal server errors in LocalMUCUser . 
ignore Update ' modules / apps / foundation / plugins - admin / . 
gh - 97 Updated CHANGELOG 
Add kotlin - gradle - plugin snapshot repo 
Add additional key for fullscreen on iOS7 
Use new sanitizer option . 
Made validation util also have private constructor to prevent initialization 
Removed any remains of list appearance 
ignore Update ' modules / apps / collaboration / wiki / . 
Mention renamed public type . 
Replace image for layout practice 5 
Updated dslv submodule 
Adding placeholders for the fullscreen button 
add html attribute 
Remove the OnItemClick listener when the fragment is destroyed . 
fixed possible IllegalStateException 
Adding whack to messenger to allow for cleaner dom implementation of basic xmpp handling . 
Removing travis configuration as builds run on Snap ! 
ignore Update ' modules / apps / collaboration / blogs / . 
ignore Update ' modules / apps / web - experience / site - navigation / . 
Updated reference to library to fix problems in login view when fixing typos in URL path 
Add string type to outerHTML . 
ignore Update ' modules / apps / foundation / portal - search / . 
updated ChangeLog 
Upgraded version in etc / pom . 
added license header 
Bumping project configuration requirement to Android 2 . 2 
add tools so that it can fetch 23 . 0 . 2 
Prepare next development stage 
ignore Update ' modules / apps / foundation / portal - security / . 
ignore Update ' modules / apps / forms - and - workflow / polls / . 
Remove local testing file 
LPS - 21453 Ignore auth token check for blogs trackback urls 
Fix checkstyle 
Updated changelog 
LPS - 65283 update jar 
ignore Update ' modules / apps / foundation / contacts / . 
Adds travis - ci configuration 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
Fixing transitive - ness of provided 
Fixed overflow rounded icon in xxhdpi 
ignore Update ' modules / apps / marketplace / . 
Add icon # 1416 
ignore Update ' modules / apps / collaboration / flags / . 
Remove the background from the RelativeLayout , allowing the ActionBar style background to show through 
make pyunit NOPASS until hadoop namenodes created . 
Moved logging configuration to the PC Facade where it belongs . 
Bumped version number to 1 . 4 . 1 
Provide ability to quickly switch soft wraps appliance at console 
Removing travis configuration as builds run on Snap ! 
Prepare next dev iteration 
update windwos bullet natives ( 32bit ) 
Bumped version 
Updated ognl to 3 . 1 . 2 
don ' t set the application title in the library 
setting version to 1 . 0 . 71 
Added a Composite Configuration Diagram to use in the Wiki . 
Added reference to distribution . 
Implement PrestoConnection . getTransactionIsolation 
Bump readme version 
Added translation using Weblate ( Uzbek ) 
Rename COPYING file to LICENSE 
remove warning 
Add ok button 
Added Joachim Baumann to the contributors 
Suppressing warnings from Boost about auto_ptr being deprecated . 
updated credits 
Updating Alloy to dcea66d ; LPS - 25276 
Fix release number 
Removing callbacks in onDetachedFromWindow , fixes b / 7465673 
Implement GradientDrawable getColorFilter . 
Fix InputType determination of WebTextView ( DO NOT MERGE ) 
Bump package . json version to 0 . 4 . 4 
rename class to match file 
add extra android support package to travis config 
patched asm 
ignore Update ' modules / apps / web - experience / staging / . 
Regenerate WSDL 
fixed issue 328 
LPS - 54745 update jar 
update libwebp 
add JSR 305 annotations jar 
Added 16x16 icon 
Bump up okhttp version 
Fix Boost install script 
add rm 
additional changes for jsonSchema moving into community , build scripts 
modify local repo to / opt / bigbluebutton / repo so it ' s more generic and match with Hudson 
Add ic_drawer for mdpi and xhdpi 
Make an internal class package private ( cherry - pick to master to unblock all ) 
Replace local copy of TimerMixin with module from npm . 
Delete screenshot_two . 
Add 888 
Fix SeekableViewsForTest to handle the reset ( long , double ) overload properly 
Ensure onCreate calls through to super . onCreate ( ) . 
fixed typo 
Remove debug spacing 
fixed break 
Updated Japanese translation 
Fix scrolling in completion lists etc . 
ignore Update ' modules / apps / web - experience / product - navigation / . 
Added debug printing content of all incoming packets 
Added target to . 
Removed new lines 
Updated gitignore to ignore hprof files 
adding more exceptions 
Added support for automatic legend generation for Wheelchair renderer 
return a blank plugin context path if it is null 
Updated README . md 
LPS - 48539 Move advice to portal - test - internal module 
fix quality gate badge location on project dashboard 
prepare release checkstyle - 7 . 3 
Updated FML 
Updated gif 
Edited CHANGELOG . md 
ignore Update ' modules / apps / foundation / users - admin / . 
Remove the TMDB API Jar from the app module 
do not log cleanup failure 
Add missing ` @ Override ` 
Add grouped barchart wiki image 
Updating Alloy to dcea66d ; LPS - 25276 
LPS - 7300 - update theming conventions 
Checking only test files 
Remove obsolete file 
Added a id to thumbnail + maincontent layout 
Change game category image . 
Setting default name for multi - project 
Remove unused import 
Added Travis 
LPS - 62881 Fix rebase 
Remove text capitalization in widget titles , closes # 1498 
Fix comment of DB migration 915 
Bump up Netty version to 4 . 0 . 12 . 
ignore Update ' modules / apps / foundation / portal - lock / . 
Add metrics constant for new settings activity 
set raptordata on added trip patterns . 
ignore Update ' modules / apps / collaboration / mentions / . 
Fixed version snapshot 
beta version = > 2 . 0 beta 12 
ignore Update ' modules / apps / web - experience / journal / . 
Smack 4 . 0 . 2 - SNAPSHOT 
ignore Update ' modules / apps / collaboration / message - boards / . 
ignore Update ' modules / apps / collaboration / document - library / . 
bumped parent versions from 2 - SNAPSHOT to 2 
Add an ensureOpen check to Publication . hasBeenConnected ( ) . 
Updated AVS proprietary to 2 . 8 . 7 
Create README . md 
Updated changelog . 
Correctly initialize animator asynchronousity 
LPS - 38482 Add missing @ Override 
add Jungtaek Lim to be sponsor of storm - redis 
ignore Update ' modules / apps / collaboration / message - boards / . 
Add image of dir tree to HAXM 
ignore Update ' modules / apps / collaboration / blogs / . 
ignore Update ' modules / apps / foundation / portal - template / . 
Changes the chat room contacts status icons . 
increased text size 
Use the correct language code for Korean 
update readme . md 
Add transition screenshots 
ignore Update ' modules / apps / collaboration / document - library / . 
Supported bash instead of sh in dserver . sh 
setting version to 1 . 0 . 106 - SNAPSHOT 
ZEPPELIN - 1308 Apache Ignite version upgraded up to 1 . 7 
ignore Update ' modules / apps / web - experience / site / . 
Corrected ` timeout ` description in the ` indices . get_aliases ` API 
Travis - restore caching 
Add one way to construct BlockStoreMeta cheaply . 
add a dummy test 
update serializer - 1 . 1 . 2 . 
Removed ItemStack import 
Add HADOOP - 12843 to 2 . 8 . 0 in CHANGES . txt . 
fix conflicting native library error message 
update readme banner img 
Hindi rendering regression in WebView 
Fix the missing return type for method references 
remove uneccessary whitespace . 
Turn debug on for test diagnosis 
add release notes 
Upgrade Ant to 1 . 9 . 6 
Removed doc / shared submodule 
Delete demo_shifting . 
LPS - 46312 Suppress warning 
ignore Update ' modules / apps / collaboration / announcements / . 
Smack 4 . 1 . 0 - rc5 
ignore Update ' modules / apps / web - experience / asset / . 
ignore Update ' modules / apps / sync / . 
increased heap 5 - > 10 
Bumping rest - client . 
Ant build improvements 
update linux amd64 natives 
Delete helloworld . meta 
removed unnecessary import 
Modify Makefile 
update handlebar to the latest mustache version 
ignore Update ' modules / apps / foundation / frontend - css / . 
ignore Update ' modules / apps / foundation / portal - search / . 
fix a bad merge 
Remove a spurious symlink 
test a change . 
update readme 
ZEPPELIN - 500 - Fix leak of output in Firefox 
Prepare next release v1 . 1 . 1 - SNAPSHOT 
Fixing GLIBC 2 . 4 problem on Debian system . 
Revert " Fixed missing import " 
update jacoco to 0 . 7 . 0 ( IDEA - 123499 ) 
Upgraded maven - release - plugin to version 2 . 1 . 
Updated github page logo 
Rename project also in < name / > 
Add Travis Build 
Fix the build 
Provide a reverseEach method for arrays 
Show hide dialog automatically 
Added banner file for README . md 
ignore Update ' modules / apps / foundation / portal - template / . 
Upgrade version library to 1 . 1 . 0 
Expose window size . 
fixed typo in changelog 
Fixed default focused element for credentials dialog opening ( password is focused if username is disabled ) 
Updated BP libs 
Revert " Changed power request to activation energy . " 
LPS - 56015 We only want the regular parameters , see getParameterValues and other methods in the class . 
Delete kk 
ignore Update ' modules / apps / foundation / portal - cache / . 
upgraded netty to 4 . 0 . 18 
ignore Update ' modules / apps / collaboration / blogs / . 
remove uuid 
Fix more type info caching bugs . 
Ignore temporary directory . 
Fix back popping the back stack too much . 
Set VERSION to 5 . 3 . 0 - dev ( via coho ) 
eliminate TODO comment 
remove swp file 
Fix travis 
Disable RenderThread 
Use the latest version of Android Tools 
ignore Update ' modules / apps / collaboration / blogs / . 
removed mislabeled file 
add STORM - 1920 to CHANGELOG 
updating astyanax version to 2 . 0 from 2 . 0 - beta 
Bump travis to build to API 25 
Changed version number so I could push the new version to dist . 
ignore Update ' modules / apps / web - experience / export - import / . 
Set ASCII as the default bundle encoding 
Fix target package name so tests run . 
Learned some new structs from Blizzard ' s Hearthstone 
Include correct redirection messages in the HAR / list returned by the API 
do not log runtimeexception 
Added manual GLProfile shutdown to make sure that no JOGL threads are 
Missing Icon files . 
Add additional clirr config 
Fix build 
update submodule 
Updated changelog 
Fix permissions 
added fix . 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
Fix memory leak 
fix win32 build break 
commented out a failing line 
Don ' t drop sentence separators . 
Removed tag roboguice - 2 . 0 - RC2b 
prepare for next development iteration 
Enable Travis for all branches 
add release notes 
Added getter for authoritiesPopulator . 
ignore Update ' modules / apps / foundation / roles / . 
removed extraneous Android Support JAR 
update gitignore 
update idea version 
Add image of ADM 
Improve MongoDB script 
Removed Merriweather light variation assets ( since they won ' t be used ) 
Make sure . 
Removed demo from library . 
update applet jar with changes to minimize connect timeout 
add a - d flag to dpkg 
Adding video link 
Update git ignore patterns . 
Added AppCompat & RecyclerView libraries 
Added bin / to ignored files for Eclipse users 
update changelog 
ignore Update ' modules / apps / foundation / osgi / . 
Add link to glm parameters list in python 
Upgrade Apache Commons Collections to v3 . 2 . 2 
Fix database version cache logic 
fixing # 184 
Remove unnecessary code . 
add changes entry about snapshot functionality 
Changed the more info link to point to the wiki . 
Add Ken to the AUTHORS file . 
Fix a typo in test log . 
remove nailed version for crate - docs - theme 
Make WAR break later in the deployment process 
Changed dependencies to milestone versions in preparation of tagging 
ignore Update ' modules / apps / collaboration / invitation / . 
setting version to 1 . 0 . 71 
Updated dslv submodule 
LPS - 55168 moves icon 
Add gitignore 
removed querydsl - scala / . 
Built new snapshot 
ignore Update ' modules / apps / foundation / frontend - theme / . 
update voiceRouter with currentStatus = STATUS_UNKNOWN ; while makeUturnWhenPossible is active 
ignore Update ' modules / apps / collaboration / image - uploader / . 
Remove assets which are no longer used . 
don ' t include grails - core in POM 
Updated Studio with last version 
Added example . 
remove unnecessary property 
Rename COPYING file to LICENSE 
update changelog for cassandra - 1201 
Changed line endings to unix since it ' s a unix file 
ignore Update ' modules / apps / web - experience / layout / . 
remove completed todo 
Added entry for SQL Injection scanner for SQLite 
Added a ms tag to the debug time system out 
Remove unknown app module 
ignore Update ' modules / apps / collaboration / document - library / . 
Fix regression in refactoring in r1706035 
updated studio with Password Validator labels fix 
update todo 
add logs / directory as require directory for base 
update emitter version 
Updated changelog 
Add warning about data volume to enable_metrics_collection 
revert fix until root cause has been found 
LRQA - 22780 Create component name for Microblogs portlet in testray 
remove tpc / lib / fastjson - 1 . 2 . 10 . 
ignore Update ' modules / apps / web - experience / export - import / . 
Bump readme version 
modified symbol for darcula ( IDEA - 99497 , IDEA - 96808 ) 
ignore Update ' modules / apps / collaboration / comment / . 
Remove commons - cli sha and add jopt - simple sha 
reset version for development 
ignore the rc file 
Fork a new test JVM every 10 classes when on cloud CI . 
Fix for broken unit test 
Set travis jdk to java8 
Use a different linker arg on windows sample 
Moved test case to hibernate - entitymanager 
Add break line 
Set default shininess value to 1 for TerrainLighting . j3md , it has to be this way to avoid an NVIDIA bug . 
LPS - 27654 - Adding Translation in Web Content in Control Panel on IE8 Breaks 
Make RUnit NOPASS until further discussion of behavior change . 
ignore Update ' modules / apps / foundation / portal / . 
ignore Update ' modules / apps / web - experience / staging / . 
Push version to 188 and 9 . 1 - beta1 . 
Now closes ReadableByteChannel after it has been read . 
Added STORM - 794 to Changelog 
Displayed a sample image properly . 
removed opengl . jar from version control 
Bump up okhttp version 
LPS - 41732 Avoid resizing image cropper on IE8 
Included haproxy in the index 
GRAILS - 6872 Provide a doctype for the default sitemesh layout , to prevent pages from being rendered in quirks mode 
Generate XML reports from JUnit test reports 
set last_subscription_check after check 
ignore Update ' modules / apps / web - experience / staging / . 
rolled back bootstrap version 
Don ' t include test data in the language statistic for a repository 
Commented maven push for travis 
ignore Update ' modules / apps / collaboration / mentions / . 
Bump version number to 1 . 0 . 0 - SNAPSHOT 
update readme 
Fix IntegerType import for Spark SQL 
ignore Update ' modules / apps / web - experience / asset / . 
spellchecker - add some common stuff to dictionary 
disabling ' Angular Templates ' plugin version 1 . 0 . 2 and 1 . 1 . 2 
Fix error in docstring 
Changed the return type of UnresolvedDependencyResult . getFailure ( ) . 
Added grails central plugin repo back in as a dependency repository . 
Fix bug in HTTP2 settings parsing 
set visible pack to empty in vcs log ui in dispose IDEA - 120539 
changed Slack channel for Travis CI 
Added files via upload 
Replicate text and sounds settings for managed profile . 
Ignore newline in format string Findbugs warnings 
Include JavaCSV in the toolkit target . 
Consolidate javax . servlet jars 
update usage plugin 
add Travis CI configurations . 
ignore Update ' modules / apps / foundation / contacts / . 
Configuration not needed any more . 
Fix Android deps for travis 
ignore Update ' modules / apps / foundation / portal - configuration / . 
ignore Update ' modules / apps / web - experience / export - import / . 
Set minHeapSize for tests in order to hopefully fail fast if there ' s not enough memory in CI environments . 
bumped version 
Switch CuratorDiscoveryConfig to not be an abstract class ' cause Jackson cannot instantiate them 
add Hungarian flag 
updated version number 
Moving STUN sources from Openfire codebase to plugin . 
Make a variable final 
if null , check version . 
Added empty line 
Added Sprint 2 comps 
fixed the re - enabling of hint ( ) 
updated version 
chore ( driver - compat ) add some error types to ignore by Clirr 
Use 2016 . 1 meta - version 
Added banner file for README . md 
Updated README . md 
Revert " Change the scope " 
Add Free Flight ringtone to source tree . 
Added tag 1 . 9 . 0 - rc1 for changeset 2cb15017027c 
Add stdint . h to fix sim - eng 
add gitignore 
Updated changelog 
Fixed onTouch in ScrollView or ViewPager 
update demo 
ignore Update ' modules / apps / foundation / portal - configuration / . 
setting version to 1 . 0 . 71 
Removed new line at the end of the file 
ignore Update ' modules / apps / foundation / frontend - theme / . 
Delete ic_launcher . 
ignore Update ' modules / apps / foundation / portal - instances / . 
include ' < cxxabi . h > ' ( needed for non - OS X platforms ) 
updated ChangeLog 
changed a typo from SHNAPSHOT to SNAPSHOT = ) 
add ConnectionState interceptor , 
Remove jobs command . 
include CoffeeScript in pycharm 2 . 0 build 
remove a space 
bump cqlsh ' s DEFAULT_CQLVER to 3 . 1 . 6 
adds STORM - 1400 
add new updated octicons 
added new device profile XML 
LPS - 56179 Create a new ResouceBundle for item - selector - web 
Update travis config 
bump version to 1 . 8 . 7 
ignore Update ' modules / apps / web - experience / trash / . 
add readme for sample app 
CORE - 1216 generateChangeLog pulls data with schema by default 
updated jar 
Add missing LOCAL_MIN_SDK_VERSION for Support Library demos 
add svm_print_interface 
Fix android_media_AudioSystem_getMasterMute return type . 
added circle . yml 
prepare for next development iteration 
ignore Update ' modules / apps / forms - and - workflow / calendar / . 
add getter for GenericVertex max index 
Still having problems with version - updated to a new one . 
Suppressed deprecation warning in the group test 
fixed rare npe after race condition 
Moved files into theme to fix broken pages . 
Bump version to 0 . 3 . 0 . 
fixing syncDoc task to avoid up - to - date message only because target directory already exists 
update internal framework to API 23 ( marshmallow ) 
Updated changelog . 
ignore Update ' modules / apps / foundation / portal - template / . 
add TODO 
Use Travis - CI ' s container based infra 
Fixed wrong usage . 
updated ChangeLog 
ignore sync - api 1 . 0 . 0 prep next 
avoid " invalid state " assertion ( IDEADEV - 21852 ) 
updated version 
added a test case for GremlinEngine . . . Going to probably rename these to GremlinScriptEngine and GremlinScriptEngineFactory to be consistent with other ScriptEngine classes . 
finished collection / list separation 
wake - up sleeping reader when stop is called 
ignore Update ' modules / apps / web - experience / layout / . 
remove empty file 
ignore Update ' modules / apps / foundation / portal - scheduler / . 
Fixed a bug in switching to freeswitch 
delete README 
Push version to 15 . 0 . 5 , 15007 . 
default focused control is OK button 
Moved logging configuration to the PC Facade where it belongs . 
ignore Update ' modules / apps / web - experience / rss / . 
Add image for preference intent 
add qt - webkit - devel dependency for yum 
update default gradle version configuration 
Bump SpongeCommon for various updates and fixes . 
ignore Update ' modules / apps / collaboration / wiki / . 
ignore Update ' modules / apps / web - experience / asset / . 
Fix UIExplorer iOS swipe back 
ignore Update ' modules / apps / sync / . 
Updated sample APK . 
Added a note about 3 . 0 . 0 compatibility 
ignore libs directory 
LPS - 57534 Should not use full path , but CI machines have a broken PATH setup , need QA to fix it . 
Fix extra - abs Gradle Build 
Add GFM input back but disable hard wrapping so we can have better formatting . 
was missing beta_features = True 
Change the flowdock notification for Travis builds . 
Set animation to null after canceling current anim . 
Updated CHANGES . txt 
Upgrade version name to 0 . 2 . 3 
Accidentally put a flow thing in h2o - 1 doc . 
added CNAME support for gh - pages 
Add Callum Stott to . 
force AST Injected property check with staticCheckerVisitor 
Fix merge issues 
Fix jdbc - jc to work with tomcat gradle plugin 
Bug 289540 added javadoc into distro 
Updated library name 
Bump up revision number . 
Ignore IntelliJ IDEA . 
Include ` private - cli ` on npm export 
upgraded guava to 16 . 0 . 1 
